"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "censys-platform"
__version__: str = "0.16.3"
__openapi_doc_version__: str = "1.0.132"
__gen_version__: str = "2.937.18"
__user_agent__: str = "speakeasy-sdk/python 0.16.3 2.937.18 1.0.132 censys-platform"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
