"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .amqp_protocol import AmqpProtocol, AmqpProtocolTypedDict
from .amqp_version import AmqpVersion, AmqpVersionTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AmqpTypedDict(TypedDict):
    explicit_tls: NotRequired[bool]
    r"""Connected via a TLS connection after initial handshake"""
    implicit_tls: NotRequired[bool]
    r"""Connected via a TLS wrapped connection (AMQPS)"""
    protocol_id: NotRequired[AmqpProtocolTypedDict]
    version: NotRequired[AmqpVersionTypedDict]


class Amqp(BaseModel):
    explicit_tls: Optional[bool] = None
    r"""Connected via a TLS connection after initial handshake"""

    implicit_tls: Optional[bool] = None
    r"""Connected via a TLS wrapped connection (AMQPS)"""

    protocol_id: Optional[AmqpProtocol] = None

    version: Optional[AmqpVersion] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["explicit_tls", "implicit_tls", "protocol_id", "version"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
