"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class AssetCertificateListInputBodyTypedDict(TypedDict):
    certificate_ids: Nullable[List[str]]
    r"""A list of SHA-256 certificate fingerprints."""


class AssetCertificateListInputBody(BaseModel):
    certificate_ids: Nullable[List[str]]
    r"""A list of SHA-256 certificate fingerprints."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
