"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, Nullable, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AssetHostListInputBodyTypedDict(TypedDict):
    host_ids: Nullable[List[str]]
    r"""A list of host IP addresses."""
    at_time: NotRequired[datetime]
    r"""RFC3339 Timestamp to view all requested hosts at a specific point in time. Must be a valid RFC3339 string. Ensure that you suffix the date with T00:00:00Z or a specific time."""


class AssetHostListInputBody(BaseModel):
    host_ids: Nullable[List[str]]
    r"""A list of host IP addresses."""

    at_time: Optional[datetime] = None
    r"""RFC3339 Timestamp to view all requested hosts at a specific point in time. Must be a valid RFC3339 string. Ensure that you suffix the date with T00:00:00Z or a specific time."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["at_time"])
        nullable_fields = set(["host_ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
