"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class BulkDeleteTagAssignmentsInputBodyTypedDict(TypedDict):
    created_after: NotRequired[datetime]
    r"""RFC3339 timestamp. Only delete assignments created after this time."""
    created_before: NotRequired[datetime]
    r"""RFC3339 timestamp. Only delete assignments created before this time."""


class BulkDeleteTagAssignmentsInputBody(BaseModel):
    created_after: Optional[datetime] = None
    r"""RFC3339 timestamp. Only delete assignments created after this time."""

    created_before: Optional[datetime] = None
    r"""RFC3339 timestamp. Only delete assignments created before this time."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["created_after", "created_before"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
