"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .censeyeresult import CenseyeResult, CenseyeResultTypedDict
from censys_platform.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CenseyeResultsResponseTypedDict(TypedDict):
    results: Nullable[List[CenseyeResultTypedDict]]
    r"""List of count results."""
    next_page_token: NotRequired[str]
    r"""Token to retrieve the next page of results."""


class CenseyeResultsResponse(BaseModel):
    results: Nullable[List[CenseyeResult]]
    r"""List of count results."""

    next_page_token: Optional[str] = None
    r"""Token to retrieve the next page of results."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["next_page_token"])
        nullable_fields = set(["results"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
