"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .censeyetarget import CenseyeTarget, CenseyeTargetTypedDict
from censys_platform import models, utils
from censys_platform.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from enum import Enum
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class State(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Current state of the job."""

    STARTED = "started"
    COMPLETED = "completed"
    FAILED = "failed"
    UNKNOWN = "unknown"


class CenseyeJobTypedDict(TypedDict):
    job_id: str
    r"""Unique identifier of the job."""
    state: State
    r"""Current state of the job."""
    target: CenseyeTargetTypedDict
    at_time: NotRequired[datetime]
    r"""The point-in-time the asset data was evaluated at."""
    create_time: NotRequired[datetime]
    r"""When the job was created."""
    delete_time: NotRequired[datetime]
    r"""When the job and results will be deleted."""
    error: NotRequired[str]
    r"""Error message if the job failed."""
    result_count: NotRequired[int]
    r"""Total number of result field-value pairs."""
    update_time: NotRequired[datetime]
    r"""When the job was last updated."""


class CenseyeJob(BaseModel):
    job_id: str
    r"""Unique identifier of the job."""

    state: State
    r"""Current state of the job."""

    target: CenseyeTarget

    at_time: Optional[datetime] = None
    r"""The point-in-time the asset data was evaluated at."""

    create_time: Optional[datetime] = None
    r"""When the job was created."""

    delete_time: Optional[datetime] = None
    r"""When the job and results will be deleted."""

    error: Optional[str] = None
    r"""Error message if the job failed."""

    result_count: Optional[int] = None
    r"""Total number of result field-value pairs."""

    update_time: Optional[datetime] = None
    r"""When the job was last updated."""

    @field_serializer("state")
    def serialize_state(self, value):
        if isinstance(value, str):
            try:
                return models.State(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "at_time",
                "create_time",
                "delete_time",
                "error",
                "result_count",
                "update_time",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
