"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ciscoipsla_handshake_header import (
    CiscoIpslaHandshakeHeader,
    CiscoIpslaHandshakeHeaderTypedDict,
)
from .ciscoipsla_handshake_message import (
    CiscoIpslaHandshakeMessage,
    CiscoIpslaHandshakeMessageTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CiscoIpslaHandshakeTypedDict(TypedDict):
    header: NotRequired[CiscoIpslaHandshakeHeaderTypedDict]
    message: NotRequired[CiscoIpslaHandshakeMessageTypedDict]


class CiscoIpslaHandshake(BaseModel):
    header: Optional[CiscoIpslaHandshakeHeader] = None

    message: Optional[CiscoIpslaHandshakeMessage] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["header", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
