"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CtRecordTypedDict(TypedDict):
    added_to_ct_at: NotRequired[str]
    r"""An RFC-3339-formatted timestamp indicating when the certificate was entered into the CT log."""
    ct_to_censys_at: NotRequired[str]
    r"""An RFC-3339-formated timestamp indicating when the certificate was ingested from the CT log into the Censys dataset."""
    index: NotRequired[int]
    r"""Numerical marker of the certificate's place in the CT log."""


class CtRecord(BaseModel):
    added_to_ct_at: Optional[str] = None
    r"""An RFC-3339-formatted timestamp indicating when the certificate was entered into the CT log."""

    ct_to_censys_at: Optional[str] = None
    r"""An RFC-3339-formated timestamp indicating when the certificate was ingested from the CT log into the Censys dataset."""

    index: Optional[int] = None
    r"""Numerical marker of the certificate's place in the CT log."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["added_to_ct_at", "ct_to_censys_at", "index"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
