"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cursorontarget_point import CursorOnTargetPoint, CursorOnTargetPointTypedDict
from .cursorontarget_status import CursorOnTargetStatus, CursorOnTargetStatusTypedDict
from .cursorontarget_takv import CursorOnTargetTakv, CursorOnTargetTakvTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CursorOnTargetEventTypedDict(TypedDict):
    callsign: NotRequired[str]
    endpoint: NotRequired[str]
    how: NotRequired[str]
    point: NotRequired[CursorOnTargetPointTypedDict]
    stale: NotRequired[str]
    start: NotRequired[str]
    status: NotRequired[CursorOnTargetStatusTypedDict]
    takv: NotRequired[CursorOnTargetTakvTypedDict]
    time: NotRequired[str]
    type: NotRequired[str]
    uid: NotRequired[str]
    version: NotRequired[str]
    video_url: NotRequired[str]


class CursorOnTargetEvent(BaseModel):
    callsign: Optional[str] = None

    endpoint: Optional[str] = None

    how: Optional[str] = None

    point: Optional[CursorOnTargetPoint] = None

    stale: Optional[str] = None

    start: Optional[str] = None

    status: Optional[CursorOnTargetStatus] = None

    takv: Optional[CursorOnTargetTakv] = None

    time: Optional[str] = None

    type: Optional[str] = None

    uid: Optional[str] = None

    version: Optional[str] = None

    video_url: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "callsign",
                "endpoint",
                "how",
                "point",
                "stale",
                "start",
                "status",
                "takv",
                "time",
                "type",
                "uid",
                "version",
                "video_url",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
