"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pixelformat import PixelFormat, PixelFormatTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DesktopInfoTypedDict(TypedDict):
    height: NotRequired[int]
    name_len: NotRequired[int]
    pixel_format: NotRequired[PixelFormatTypedDict]
    width: NotRequired[int]


class DesktopInfo(BaseModel):
    height: Optional[int] = None

    name_len: Optional[int] = None

    pixel_format: Optional[PixelFormat] = None

    width: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["height", "name_len", "pixel_format", "width"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
