"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dicom_aabort import DicomAAbort, DicomAAbortTypedDict
from .dicom_associateac import DicomAssociateAc, DicomAssociateAcTypedDict
from .dicom_associaterj import DicomAssociateRj, DicomAssociateRjTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DicomTypedDict(TypedDict):
    a_abort: NotRequired[DicomAAbortTypedDict]
    associate_ac: NotRequired[DicomAssociateAcTypedDict]
    associate_rj: NotRequired[DicomAssociateRjTypedDict]
    pdu_type_name: NotRequired[str]


class Dicom(BaseModel):
    a_abort: Optional[DicomAAbort] = None

    associate_ac: Optional[DicomAssociateAc] = None

    associate_rj: Optional[DicomAssociateRj] = None

    pdu_type_name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["a_abort", "associate_ac", "associate_rj", "pdu_type_name"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
