"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform import models, utils
from censys_platform.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DNSResourceRecordType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""An enumerated field indicating what type of data is in the \"services.dns.additionals.response\" field. For example, \"A\" signifies that the value in \"services.dns.additionals.response\" is an IPv4 address for the FQDN in \"services.dns.additionals.name\"."""

    UNKNOWN = ""
    A = "a"
    TXT = "txt"
    NS = "ns"


class DNSResourceRecordTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The Fully Qualified Domain Name (FQDN) this RR is for."""
    response: NotRequired[str]
    r"""The RDATA field of the RR."""
    type: NotRequired[DNSResourceRecordType]
    r"""An enumerated field indicating what type of data is in the \"services.dns.additionals.response\" field. For example, \"A\" signifies that the value in \"services.dns.additionals.response\" is an IPv4 address for the FQDN in \"services.dns.additionals.name\"."""


class DNSResourceRecord(BaseModel):
    name: Optional[str] = None
    r"""The Fully Qualified Domain Name (FQDN) this RR is for."""

    response: Optional[str] = None
    r"""The RDATA field of the RR."""

    type: Optional[DNSResourceRecordType] = None
    r"""An enumerated field indicating what type of data is in the \"services.dns.additionals.response\" field. For example, \"A\" signifies that the value in \"services.dns.additionals.response\" is an IPv4 address for the FQDN in \"services.dns.additionals.name\"."""

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.DNSResourceRecordType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "response", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
