"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dnsipresolutionrangerecord import (
    DNSIPResolutionRangeRecord,
    DNSIPResolutionRangeRecordTypedDict,
)
from censys_platform.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class DNSIPResolutionRangeResponseTypedDict(TypedDict):
    ip: str
    r"""The IP address that was queried."""
    next_page_token: str
    r"""A token that can be used to retrieve the next page of records."""
    records: Nullable[List[DNSIPResolutionRangeRecordTypedDict]]
    r"""The list of domain names that resolved to this IP."""
    total_records: int
    r"""The number of records that exist in total across all pages."""


class DNSIPResolutionRangeResponse(BaseModel):
    ip: str
    r"""The IP address that was queried."""

    next_page_token: str
    r"""A token that can be used to retrieve the next page of records."""

    records: Nullable[List[DNSIPResolutionRangeRecord]]
    r"""The list of domain names that resolved to this IP."""

    total_records: int
    r"""The number of records that exist in total across all pages."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
