"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform import models, utils
from censys_platform.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from enum import Enum
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DNSResolutionRecordRecordType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The record type. Either A, AAAA, MX, NS, SOA, or TXT."""

    A = "A"
    AAAA = "AAAA"
    MX = "MX"
    NS = "NS"
    SOA = "SOA"
    TXT = "TXT"


class DNSResolutionRecordTypedDict(TypedDict):
    first_seen: datetime
    r"""The time this record was first observed."""
    last_seen: datetime
    r"""The time this record was last observed."""
    record_type: DNSResolutionRecordRecordType
    r"""The record type. Either A, AAAA, MX, NS, SOA, or TXT."""
    ip: NotRequired[str]
    r"""The IP of the record. IPv4 if the record_type is A. IPv6 if the record_type is AAAA. Otherwise not present."""
    mail_server: NotRequired[str]
    r"""The MX mail server. Only present when record_type is MX. Otherwise not present."""
    mname: NotRequired[str]
    r"""The primary name server. Only present when record_type is SOA. Otherwise not present."""
    name_server: NotRequired[str]
    r"""The name server. Only present when record_type is NS. Otherwise not present."""
    priority: NotRequired[int]
    r"""The MX priority. Only present when record_type is MX. Otherwise not present."""
    rname: NotRequired[str]
    r"""The responsible contact, as email. Only present when record_type is SOA. Otherwise not present."""
    value: NotRequired[str]
    r"""Full, untruncated string. Only present when record_type is TXT. Otherwise not present."""


class DNSResolutionRecord(BaseModel):
    first_seen: datetime
    r"""The time this record was first observed."""

    last_seen: datetime
    r"""The time this record was last observed."""

    record_type: DNSResolutionRecordRecordType
    r"""The record type. Either A, AAAA, MX, NS, SOA, or TXT."""

    ip: Optional[str] = None
    r"""The IP of the record. IPv4 if the record_type is A. IPv6 if the record_type is AAAA. Otherwise not present."""

    mail_server: Optional[str] = None
    r"""The MX mail server. Only present when record_type is MX. Otherwise not present."""

    mname: Optional[str] = None
    r"""The primary name server. Only present when record_type is SOA. Otherwise not present."""

    name_server: Optional[str] = None
    r"""The name server. Only present when record_type is NS. Otherwise not present."""

    priority: Optional[int] = None
    r"""The MX priority. Only present when record_type is MX. Otherwise not present."""

    rname: Optional[str] = None
    r"""The responsible contact, as email. Only present when record_type is SOA. Otherwise not present."""

    value: Optional[str] = None
    r"""Full, untruncated string. Only present when record_type is TXT. Otherwise not present."""

    @field_serializer("record_type")
    def serialize_record_type(self, value):
        if isinstance(value, str):
            try:
                return models.DNSResolutionRecordRecordType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["ip", "mail_server", "mname", "name_server", "priority", "rname", "value"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
