"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EipServiceTypedDict(TypedDict):
    capabilities: NotRequired[int]
    service_name: NotRequired[str]
    supports_tcp: NotRequired[bool]
    supports_udp: NotRequired[bool]


class EipService(BaseModel):
    capabilities: Optional[int] = None

    service_name: Optional[str] = None

    supports_tcp: Optional[bool] = None

    supports_udp: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["capabilities", "service_name", "supports_tcp", "supports_udp"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
