"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .elasticsearch_resultsnodeinfo_nodes_nodedata_nodesettings_node_attr_ml import (
    ElasticSearchResultsNodeInfoNodesNodeDataNodeSettingsNodeAttrML,
    ElasticSearchResultsNodeInfoNodesNodeDataNodeSettingsNodeAttrMLTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ElasticSearchResultsNodeInfoNodesNodeDataNodeSettingsNodeAttrTypedDict(TypedDict):
    ml: NotRequired[
        ElasticSearchResultsNodeInfoNodesNodeDataNodeSettingsNodeAttrMLTypedDict
    ]
    xpack_installed: NotRequired[str]


class ElasticSearchResultsNodeInfoNodesNodeDataNodeSettingsNodeAttr(BaseModel):
    ml: Optional[ElasticSearchResultsNodeInfoNodesNodeDataNodeSettingsNodeAttrML] = None

    xpack_installed: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ml", "xpack_installed"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
