"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ElasticSearchResultsNodeInfoNodesNodeDataModulesTypedDict(TypedDict):
    class_name: NotRequired[str]
    desc: NotRequired[str]
    elastic_version: NotRequired[str]
    ext_plugins: NotRequired[Nullable[List[str]]]
    has_native_ctrl: NotRequired[bool]
    java_version: NotRequired[str]
    name: NotRequired[str]
    version: NotRequired[str]


class ElasticSearchResultsNodeInfoNodesNodeDataModules(BaseModel):
    class_name: Optional[str] = None

    desc: Optional[str] = None

    elastic_version: Optional[str] = None

    ext_plugins: OptionalNullable[List[str]] = UNSET

    has_native_ctrl: Optional[bool] = None

    java_version: Optional[str] = None

    name: Optional[str] = None

    version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "class_name",
                "desc",
                "elastic_version",
                "ext_plugins",
                "has_native_ctrl",
                "java_version",
                "name",
                "version",
            ]
        )
        nullable_fields = set(["ext_plugins"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
