"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .elasticsearch_resultsnodeinfo_nodes_nodedata_jvm import (
    ElasticSearchResultsNodeInfoNodesNodeDataJVM,
    ElasticSearchResultsNodeInfoNodesNodeDataJVMTypedDict,
)
from .elasticsearch_resultsnodeinfo_nodes_nodedata_modules import (
    ElasticSearchResultsNodeInfoNodesNodeDataModules,
    ElasticSearchResultsNodeInfoNodesNodeDataModulesTypedDict,
)
from .elasticsearch_resultsnodeinfo_nodes_nodedata_nodesettings import (
    ElasticSearchResultsNodeInfoNodesNodeDataNodeSettings,
    ElasticSearchResultsNodeInfoNodesNodeDataNodeSettingsTypedDict,
)
from .elasticsearch_resultsnodeinfo_nodes_nodedata_os import (
    ElasticSearchResultsNodeInfoNodesNodeDataOS,
    ElasticSearchResultsNodeInfoNodesNodeDataOSTypedDict,
)
from .elasticsearch_resultsnodeinfo_nodes_nodedata_threadpool import (
    ElasticSearchResultsNodeInfoNodesNodeDataThreadPool,
    ElasticSearchResultsNodeInfoNodesNodeDataThreadPoolTypedDict,
)
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ElasticSearchResultsNodeInfoNodesNodeDataTypedDict(TypedDict):
    build_flavor: NotRequired[str]
    build_hash: NotRequired[str]
    build_type: NotRequired[str]
    host: NotRequired[str]
    ingest_processors: NotRequired[Nullable[List[str]]]
    ip: NotRequired[str]
    ip_raw: NotRequired[str]
    jvm: NotRequired[ElasticSearchResultsNodeInfoNodesNodeDataJVMTypedDict]
    modules: NotRequired[
        Nullable[List[ElasticSearchResultsNodeInfoNodesNodeDataModulesTypedDict]]
    ]
    name: NotRequired[str]
    os: NotRequired[ElasticSearchResultsNodeInfoNodesNodeDataOSTypedDict]
    roles: NotRequired[Nullable[List[str]]]
    settings: NotRequired[
        ElasticSearchResultsNodeInfoNodesNodeDataNodeSettingsTypedDict
    ]
    thread_pool_list: NotRequired[
        Nullable[List[ElasticSearchResultsNodeInfoNodesNodeDataThreadPoolTypedDict]]
    ]
    total_indexing_buffer: NotRequired[int]
    version: NotRequired[str]


class ElasticSearchResultsNodeInfoNodesNodeData(BaseModel):
    build_flavor: Optional[str] = None

    build_hash: Optional[str] = None

    build_type: Optional[str] = None

    host: Optional[str] = None

    ingest_processors: OptionalNullable[List[str]] = UNSET

    ip: Optional[str] = None

    ip_raw: Optional[str] = None

    jvm: Optional[ElasticSearchResultsNodeInfoNodesNodeDataJVM] = None

    modules: OptionalNullable[
        List[ElasticSearchResultsNodeInfoNodesNodeDataModules]
    ] = UNSET

    name: Optional[str] = None

    os: Optional[ElasticSearchResultsNodeInfoNodesNodeDataOS] = None

    roles: OptionalNullable[List[str]] = UNSET

    settings: Optional[ElasticSearchResultsNodeInfoNodesNodeDataNodeSettings] = None

    thread_pool_list: OptionalNullable[
        List[ElasticSearchResultsNodeInfoNodesNodeDataThreadPool]
    ] = UNSET

    total_indexing_buffer: Optional[int] = None

    version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "build_flavor",
                "build_hash",
                "build_type",
                "host",
                "ingest_processors",
                "ip",
                "ip_raw",
                "jvm",
                "modules",
                "name",
                "os",
                "roles",
                "settings",
                "thread_pool_list",
                "total_indexing_buffer",
                "version",
            ]
        )
        nullable_fields = set(
            ["ingest_processors", "modules", "roles", "thread_pool_list"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
