"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .elasticsearch_errormessage import (
    ElasticSearchErrorMessage,
    ElasticSearchErrorMessageTypedDict,
)
from .elasticsearch_resultsnodeinfo import (
    ElasticSearchResultsNodeInfo,
    ElasticSearchResultsNodeInfoTypedDict,
)
from .elasticsearch_systeminfo import (
    ElasticSearchSystemInfo,
    ElasticSearchSystemInfoTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ElasticSearchTypedDict(TypedDict):
    error_message: NotRequired[ElasticSearchErrorMessageTypedDict]
    results_node_info: NotRequired[ElasticSearchResultsNodeInfoTypedDict]
    system_info: NotRequired[ElasticSearchSystemInfoTypedDict]


class ElasticSearch(BaseModel):
    error_message: Optional[ElasticSearchErrorMessage] = None

    results_node_info: Optional[ElasticSearchResultsNodeInfo] = None

    system_info: Optional[ElasticSearchSystemInfo] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error_message", "results_node_info", "system_info"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
