"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ExportTypedDict(TypedDict):
    details: NotRequired[str]
    max_payload_size: NotRequired[int]
    min_block_size: NotRequired[int]
    name: NotRequired[str]
    preferred_block_size: NotRequired[int]
    size: NotRequired[int]
    transmit_flags: NotRequired[Nullable[List[str]]]


class Export(BaseModel):
    details: Optional[str] = None

    max_payload_size: Optional[int] = None

    min_block_size: Optional[int] = None

    name: Optional[str] = None

    preferred_block_size: Optional[int] = None

    size: Optional[int] = None

    transmit_flags: OptionalNullable[List[str]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "details",
                "max_payload_size",
                "min_block_size",
                "name",
                "preferred_block_size",
                "size",
                "transmit_flags",
            ]
        )
        nullable_fields = set(["transmit_flags"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
