"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ExtractedEndpointDataCopyrightTypedDict(TypedDict):
    end_year: NotRequired[int]
    holder: NotRequired[str]
    start_year: NotRequired[int]
    text: NotRequired[str]


class ExtractedEndpointDataCopyright(BaseModel):
    end_year: Optional[int] = None

    holder: Optional[str] = None

    start_year: Optional[int] = None

    text: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["end_year", "holder", "start_year", "text"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
