"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .extractedendpointdata_analyticsservice import (
    ExtractedEndpointDataAnalyticsService,
    ExtractedEndpointDataAnalyticsServiceTypedDict,
)
from .extractedendpointdata_copyright import (
    ExtractedEndpointDataCopyright,
    ExtractedEndpointDataCopyrightTypedDict,
)
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class ExtractedEndpointDataTypedDict(TypedDict):
    analytics_services: NotRequired[
        Nullable[List[ExtractedEndpointDataAnalyticsServiceTypedDict]]
    ]
    copyrights: NotRequired[Nullable[List[ExtractedEndpointDataCopyrightTypedDict]]]
    ip_addresses: NotRequired[Nullable[List[str]]]
    languages: NotRequired[Nullable[List[str]]]
    links: NotRequired[Nullable[List[str]]]
    mac_addresses: NotRequired[Nullable[List[str]]]


class ExtractedEndpointData(BaseModel):
    analytics_services: OptionalNullable[
        List[ExtractedEndpointDataAnalyticsService]
    ] = UNSET

    copyrights: OptionalNullable[List[ExtractedEndpointDataCopyright]] = UNSET

    ip_addresses: OptionalNullable[List[str]] = UNSET

    languages: OptionalNullable[List[str]] = UNSET

    links: OptionalNullable[List[str]] = UNSET

    mac_addresses: OptionalNullable[List[str]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "analytics_services",
                "copyrights",
                "ip_addresses",
                "languages",
                "links",
                "mac_addresses",
            ]
        )
        nullable_fields = set(
            [
                "analytics_services",
                "copyrights",
                "ip_addresses",
                "languages",
                "links",
                "mac_addresses",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
