"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class FlashSocketPolicyAllowAccessFromTypedDict(TypedDict):
    domain: NotRequired[str]
    secure: NotRequired[bool]
    to_ports: NotRequired[str]


class FlashSocketPolicyAllowAccessFrom(BaseModel):
    domain: Optional[str] = None

    secure: Optional[bool] = None

    to_ports: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["domain", "secure", "to_ports"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
