"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .flashsocketpolicy_allowaccessfrom import (
    FlashSocketPolicyAllowAccessFrom,
    FlashSocketPolicyAllowAccessFromTypedDict,
)
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class FlashSocketPolicyTypedDict(TypedDict):
    allow_access_from: NotRequired[
        Nullable[List[FlashSocketPolicyAllowAccessFromTypedDict]]
    ]
    policy: NotRequired[str]
    site_control: NotRequired[str]


class FlashSocketPolicy(BaseModel):
    allow_access_from: OptionalNullable[List[FlashSocketPolicyAllowAccessFrom]] = UNSET

    policy: Optional[str] = None

    site_control: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["allow_access_from", "policy", "site_control"])
        nullable_fields = set(["allow_access_from"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
