"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class FortigateTypedDict(TypedDict):
    api_version: NotRequired[str]
    build: NotRequired[int]
    serial: NotRequired[str]
    status_code: NotRequired[int]
    status_msg: NotRequired[str]
    version: NotRequired[str]


class Fortigate(BaseModel):
    api_version: Optional[str] = None

    build: Optional[int] = None

    serial: Optional[str] = None

    status_code: Optional[int] = None

    status_msg: Optional[str] = None

    version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["api_version", "build", "serial", "status_code", "status_msg", "version"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
