"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class FtpTypedDict(TypedDict):
    auth_ssl_response: NotRequired[str]
    auth_tls_response: NotRequired[str]
    implicit_tls: NotRequired[bool]
    status_code: NotRequired[int]
    status_meaning: NotRequired[str]


class Ftp(BaseModel):
    auth_ssl_response: Optional[str] = None

    auth_tls_response: Optional[str] = None

    implicit_tls: Optional[bool] = None

    status_code: Optional[int] = None

    status_meaning: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "auth_ssl_response",
                "auth_tls_response",
                "implicit_tls",
                "status_code",
                "status_meaning",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
