"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .greynoise_tag import GreynoiseTag, GreynoiseTagTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GreynoiseTypedDict(TypedDict):
    actor: NotRequired[str]
    r"""The actor that was observed."""
    classification: NotRequired[str]
    r"""The classification of the IP address."""
    tags: NotRequired[Nullable[List[GreynoiseTagTypedDict]]]
    r"""The tags associated with the IP address."""


class Greynoise(BaseModel):
    actor: Optional[str] = None
    r"""The actor that was observed."""

    classification: Optional[str] = None
    r"""The classification of the IP address."""

    tags: OptionalNullable[List[GreynoiseTag]] = UNSET
    r"""The tags associated with the IP address."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["actor", "classification", "tags"])
        nullable_fields = set(["tags"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
