"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hikvision_platform import HikvisionPlatform, HikvisionPlatformTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class HikvisionTypedDict(TypedDict):
    custom_version: NotRequired[str]
    platforms: NotRequired[Nullable[List[HikvisionPlatformTypedDict]]]
    plugin_version: NotRequired[str]
    web_version: NotRequired[str]


class Hikvision(BaseModel):
    custom_version: Optional[str] = None

    platforms: OptionalNullable[List[HikvisionPlatform]] = UNSET

    plugin_version: Optional[str] = None

    web_version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["custom_version", "platforms", "plugin_version", "web_version"]
        )
        nullable_fields = set(["platforms"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
