"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hostdns import HostDNS, HostDNSTypedDict
from .hostenrichmentservice import HostEnrichmentService, HostEnrichmentServiceTypedDict
from .label import Label, LabelTypedDict
from .location import Location, LocationTypedDict
from .networkclassification import NetworkClassification, NetworkClassificationTypedDict
from .privacy import Privacy, PrivacyTypedDict
from .reputation import Reputation, ReputationTypedDict
from .routing import Routing, RoutingTypedDict
from .thirdparty import ThirdParty, ThirdPartyTypedDict
from .whois import Whois, WhoisTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class HostEnrichmentTypedDict(TypedDict):
    autonomous_system: NotRequired[RoutingTypedDict]
    dns: NotRequired[HostDNSTypedDict]
    ip: NotRequired[str]
    labels: NotRequired[Nullable[List[LabelTypedDict]]]
    location: NotRequired[LocationTypedDict]
    network: NotRequired[Nullable[List[NetworkClassificationTypedDict]]]
    r"""Information about what type of network the host belongs to."""
    privacy: NotRequired[Nullable[List[PrivacyTypedDict]]]
    r"""Information about privacy services used by the IP, such as VPNs, Proxies, or Tor."""
    reputation: NotRequired[ReputationTypedDict]
    service_count: NotRequired[int]
    services: NotRequired[Nullable[List[HostEnrichmentServiceTypedDict]]]
    third_party: NotRequired[ThirdPartyTypedDict]
    whois: NotRequired[WhoisTypedDict]


class HostEnrichment(BaseModel):
    autonomous_system: Optional[Routing] = None

    dns: Optional[HostDNS] = None

    ip: Optional[str] = None

    labels: OptionalNullable[List[Label]] = UNSET

    location: Optional[Location] = None

    network: OptionalNullable[List[NetworkClassification]] = UNSET
    r"""Information about what type of network the host belongs to."""

    privacy: OptionalNullable[List[Privacy]] = UNSET
    r"""Information about privacy services used by the IP, such as VPNs, Proxies, or Tor."""

    reputation: Optional[Reputation] = None

    service_count: Optional[int] = None

    services: OptionalNullable[List[HostEnrichmentService]] = UNSET

    third_party: Optional[ThirdParty] = None

    whois: Optional[Whois] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "autonomous_system",
                "dns",
                "ip",
                "labels",
                "location",
                "network",
                "privacy",
                "reputation",
                "service_count",
                "services",
                "third_party",
                "whois",
            ]
        )
        nullable_fields = set(["labels", "network", "privacy", "services"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
