"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform import models, utils
from censys_platform.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RecordType(str, Enum, metaclass=utils.OpenEnumMeta):
    UNKNOWN = ""
    A = "a"
    AAAA = "aaaa"


class HostDNSForwardResolutionTypedDict(TypedDict):
    name: NotRequired[str]
    record_type: NotRequired[RecordType]
    resolve_time: NotRequired[str]
    server: NotRequired[str]


class HostDNSForwardResolution(BaseModel):
    name: Optional[str] = None

    record_type: Optional[RecordType] = None

    resolve_time: Optional[str] = None

    server: Optional[str] = None

    @field_serializer("record_type")
    def serialize_record_type(self, value):
        if isinstance(value, str):
            try:
                return models.RecordType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "record_type", "resolve_time", "server"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
