"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .attribute import Attribute, AttributeTypedDict
from .greynoise import Greynoise, GreynoiseTypedDict
from .hostdns import HostDNS, HostDNSTypedDict
from .label import Label, LabelTypedDict
from .location import Location, LocationTypedDict
from .networkclassification import NetworkClassification, NetworkClassificationTypedDict
from .privacy import Privacy, PrivacyTypedDict
from .reputation import Reputation, ReputationTypedDict
from .routing import Routing, RoutingTypedDict
from .service import Service, ServiceTypedDict
from .whois import Whois, WhoisTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class HostTypedDict(TypedDict):
    autonomous_system: NotRequired[RoutingTypedDict]
    dns: NotRequired[HostDNSTypedDict]
    greynoise: NotRequired[GreynoiseTypedDict]
    hardware: NotRequired[AttributeTypedDict]
    ip: NotRequired[str]
    labels: NotRequired[Nullable[List[LabelTypedDict]]]
    location: NotRequired[LocationTypedDict]
    network: NotRequired[Nullable[List[NetworkClassificationTypedDict]]]
    r"""Information about what type of network the host belongs to."""
    operating_system: NotRequired[AttributeTypedDict]
    privacy: NotRequired[Nullable[List[PrivacyTypedDict]]]
    r"""Information about privacy services used by the IP, such as VPNs, Proxies, or Tor."""
    reputation: NotRequired[ReputationTypedDict]
    service_count: NotRequired[int]
    services: NotRequired[Nullable[List[ServiceTypedDict]]]
    whois: NotRequired[WhoisTypedDict]


class Host(BaseModel):
    autonomous_system: Optional[Routing] = None

    dns: Optional[HostDNS] = None

    greynoise: Optional[Greynoise] = None

    hardware: Optional[Attribute] = None

    ip: Optional[str] = None

    labels: OptionalNullable[List[Label]] = UNSET

    location: Optional[Location] = None

    network: OptionalNullable[List[NetworkClassification]] = UNSET
    r"""Information about what type of network the host belongs to."""

    operating_system: Optional[Attribute] = None

    privacy: OptionalNullable[List[Privacy]] = UNSET
    r"""Information about privacy services used by the IP, such as VPNs, Proxies, or Tor."""

    reputation: Optional[Reputation] = None

    service_count: Optional[int] = None

    services: OptionalNullable[List[Service]] = UNSET

    whois: Optional[Whois] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "autonomous_system",
                "dns",
                "greynoise",
                "hardware",
                "ip",
                "labels",
                "location",
                "network",
                "operating_system",
                "privacy",
                "reputation",
                "service_count",
                "services",
                "whois",
            ]
        )
        nullable_fields = set(["labels", "network", "privacy", "services"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
