"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hostdns_forwardresolution import (
    HostDNSForwardResolution,
    HostDNSForwardResolutionTypedDict,
)
from .hostdns_reverseresolution import (
    HostDNSReverseResolution,
    HostDNSReverseResolutionTypedDict,
)
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class HostDNSTypedDict(TypedDict):
    forward_dns: NotRequired[Dict[str, HostDNSForwardResolutionTypedDict]]
    names: NotRequired[Nullable[List[str]]]
    reverse_dns: NotRequired[HostDNSReverseResolutionTypedDict]


class HostDNS(BaseModel):
    forward_dns: Optional[Dict[str, HostDNSForwardResolution]] = None

    names: OptionalNullable[List[str]] = UNSET

    reverse_dns: Optional[HostDNSReverseResolution] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["forward_dns", "names", "reverse_dns"])
        nullable_fields = set(["names"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
