"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform import models, utils
from censys_platform.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class HTTPRedirectChainLinkTransportProtocol(str, Enum, metaclass=utils.OpenEnumMeta):
    UNKNOWN = ""
    TCP = "tcp"
    UDP = "udp"
    ICMP = "icmp"
    QUIC = "quic"


class HTTPRedirectChainLinkTypedDict(TypedDict):
    hostname: NotRequired[str]
    path: NotRequired[str]
    port: NotRequired[int]
    reason: NotRequired[str]
    scheme: NotRequired[str]
    transport_protocol: NotRequired[HTTPRedirectChainLinkTransportProtocol]


class HTTPRedirectChainLink(BaseModel):
    hostname: Optional[str] = None

    path: Optional[str] = None

    port: Optional[int] = None

    reason: Optional[str] = None

    scheme: Optional[str] = None

    transport_protocol: Optional[HTTPRedirectChainLinkTransportProtocol] = None

    @field_serializer("transport_protocol")
    def serialize_transport_protocol(self, value):
        if isinstance(value, str):
            try:
                return models.HTTPRedirectChainLinkTransportProtocol(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["hostname", "path", "port", "reason", "scheme", "transport_protocol"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
