"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .iec608705104_apci import Iec608705104Apci, Iec608705104ApciTypedDict
from .iec608705104_asdu import Iec608705104Asdu, Iec608705104AsduTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Iec608705104TypedDict(TypedDict):
    apci: NotRequired[Iec608705104ApciTypedDict]
    asdu: NotRequired[Iec608705104AsduTypedDict]


class Iec608705104(BaseModel):
    apci: Optional[Iec608705104Apci] = None

    asdu: Optional[Iec608705104Asdu] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["apci", "asdu"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
