"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Iec608705104ApciTypedDict(TypedDict):
    format_: NotRequired[str]
    u_subtype: NotRequired[str]


class Iec608705104Apci(BaseModel):
    format_: Annotated[Optional[str], pydantic.Field(alias="format")] = None

    u_subtype: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["format", "u_subtype"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Iec608705104Apci.model_rebuild()
except NameError:
    pass
