"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ike_v1 import IkeV1, IkeV1TypedDict
from .ike_v2 import IkeV2, IkeV2TypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class IkeTypedDict(TypedDict):
    v1: NotRequired[IkeV1TypedDict]
    v2: NotRequired[IkeV2TypedDict]


class Ike(BaseModel):
    v1: Optional[IkeV1] = None

    v2: Optional[IkeV2] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["v1", "v2"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
