"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ipmi_commandpayload_commandnumber import (
    IpmiCommandPayloadCommandNumber,
    IpmiCommandPayloadCommandNumberTypedDict,
)
from .ipmi_commandpayload_packednetfn import (
    IpmiCommandPayloadPackedNetFn,
    IpmiCommandPayloadPackedNetFnTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class IpmiCommandPayloadTypedDict(TypedDict):
    checksum_error: NotRequired[bool]
    r"""This is set to true if the values of chk1 / chk2 do not match the command data"""
    data: NotRequired[str]
    r"""The raw data. On success, this should be the value of the GetAuthenticationCapabilities resopnse"""
    ipmi_command_number: NotRequired[IpmiCommandPayloadCommandNumberTypedDict]
    network_function_code: NotRequired[IpmiCommandPayloadPackedNetFnTypedDict]
    requestor_sequence_number: NotRequired[int]
    r"""The request sequence number."""


class IpmiCommandPayload(BaseModel):
    checksum_error: Optional[bool] = None
    r"""This is set to true if the values of chk1 / chk2 do not match the command data"""

    data: Optional[str] = None
    r"""The raw data. On success, this should be the value of the GetAuthenticationCapabilities resopnse"""

    ipmi_command_number: Optional[IpmiCommandPayloadCommandNumber] = None

    network_function_code: Optional[IpmiCommandPayloadPackedNetFn] = None

    requestor_sequence_number: Optional[int] = None
    r"""The request sequence number."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "checksum_error",
                "data",
                "ipmi_command_number",
                "network_function_code",
                "requestor_sequence_number",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
