"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .fielddiff import FieldDiff, FieldDiffTypedDict
from .jarmscan import JarmScan, JarmScanTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class JarmScannedTypedDict(TypedDict):
    diff: NotRequired[Dict[str, FieldDiffTypedDict]]
    scan: NotRequired[JarmScanTypedDict]


class JarmScanned(BaseModel):
    diff: Optional[Dict[str, FieldDiff]] = None

    scan: Optional[JarmScan] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["diff", "scan"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
