"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jenkins_job import JenkinsJob, JenkinsJobTypedDict
from .jenkins_label import JenkinsLabel, JenkinsLabelTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class JenkinsTypedDict(TypedDict):
    assigned_labels: NotRequired[Nullable[List[JenkinsLabelTypedDict]]]
    jobs: NotRequired[Nullable[List[JenkinsJobTypedDict]]]
    mode: NotRequired[str]
    node_description: NotRequired[str]
    node_name: NotRequired[str]
    slave_agent_port: NotRequired[int]
    use_security: NotRequired[bool]


class Jenkins(BaseModel):
    assigned_labels: OptionalNullable[List[JenkinsLabel]] = UNSET

    jobs: OptionalNullable[List[JenkinsJob]] = UNSET

    mode: Optional[str] = None

    node_description: Optional[str] = None

    node_name: Optional[str] = None

    slave_agent_port: Optional[int] = None

    use_security: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "assigned_labels",
                "jobs",
                "mode",
                "node_description",
                "node_name",
                "slave_agent_port",
                "use_security",
            ]
        )
        nullable_fields = set(["assigned_labels", "jobs"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
