"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class KnxipDeviceInfoTypedDict(TypedDict):
    device_status: NotRequired[str]
    friendly_name: NotRequired[str]
    individual_address: NotRequired[str]
    knx_medium: NotRequired[str]
    mac_address: NotRequired[str]
    multicast_address: NotRequired[str]
    project_installation_id: NotRequired[int]
    serial_number: NotRequired[str]


class KnxipDeviceInfo(BaseModel):
    device_status: Optional[str] = None

    friendly_name: Optional[str] = None

    individual_address: Optional[str] = None

    knx_medium: Optional[str] = None

    mac_address: Optional[str] = None

    multicast_address: Optional[str] = None

    project_installation_id: Optional[int] = None

    serial_number: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "device_status",
                "friendly_name",
                "individual_address",
                "knx_medium",
                "mac_address",
                "multicast_address",
                "project_installation_id",
                "serial_number",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
