"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class KubernetesNodeNodeAddressTypedDict(TypedDict):
    address: NotRequired[str]
    r"""Node address, IP/URL."""
    address_type: NotRequired[str]
    r"""Node address type, one of Hostname, ExternalIP or InternalIP."""


class KubernetesNodeNodeAddress(BaseModel):
    address: Optional[str] = None
    r"""Node address, IP/URL."""

    address_type: Optional[str] = None
    r"""Node address type, one of Hostname, ExternalIP or InternalIP."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["address", "address_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
