"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .kubernetes_node_nodeaddress import (
    KubernetesNodeNodeAddress,
    KubernetesNodeNodeAddressTypedDict,
)
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class KubernetesNodeTypedDict(TypedDict):
    addresses: NotRequired[Nullable[List[KubernetesNodeNodeAddressTypedDict]]]
    architecture: NotRequired[str]
    r"""The Architecture reported by the node."""
    container_runtime_version: NotRequired[str]
    r"""ContainerRuntime Version reported by the node through runtime remote API (e.g. docker://1.5.0)."""
    images: NotRequired[Nullable[List[str]]]
    r"""List of container images on this node"""
    kernel_version: NotRequired[str]
    r"""Kernel Version reported by the node from 'uname -r' (e.g. 3.16.0-0.bpo.4-amd64)."""
    kube_proxy_version: NotRequired[str]
    r"""KubeProxy Version reported by the node."""
    kubelet_version: NotRequired[str]
    r"""Kubelet Version reported by the node."""
    name: NotRequired[str]
    operating_system: NotRequired[str]
    r"""The Operating System reported by the node."""
    os_image: NotRequired[str]
    r"""OS Image reported by the node from /etc/os-release (e.g. Debian GNU/Linux 7 (wheezy))."""


class KubernetesNode(BaseModel):
    addresses: OptionalNullable[List[KubernetesNodeNodeAddress]] = UNSET

    architecture: Optional[str] = None
    r"""The Architecture reported by the node."""

    container_runtime_version: Optional[str] = None
    r"""ContainerRuntime Version reported by the node through runtime remote API (e.g. docker://1.5.0)."""

    images: OptionalNullable[List[str]] = UNSET
    r"""List of container images on this node"""

    kernel_version: Optional[str] = None
    r"""Kernel Version reported by the node from 'uname -r' (e.g. 3.16.0-0.bpo.4-amd64)."""

    kube_proxy_version: Optional[str] = None
    r"""KubeProxy Version reported by the node."""

    kubelet_version: Optional[str] = None
    r"""Kubelet Version reported by the node."""

    name: Optional[str] = None

    operating_system: Optional[str] = None
    r"""The Operating System reported by the node."""

    os_image: Optional[str] = None
    r"""OS Image reported by the node from /etc/os-release (e.g. Debian GNU/Linux 7 (wheezy))."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "addresses",
                "architecture",
                "container_runtime_version",
                "images",
                "kernel_version",
                "kube_proxy_version",
                "kubelet_version",
                "name",
                "operating_system",
                "os_image",
            ]
        )
        nullable_fields = set(["addresses", "images"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
