"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .malloryai_opinion_attributes import (
    MalloryAIOpinionAttributes,
    MalloryAIOpinionAttributesTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MalloryAIOpinionTypedDict(TypedDict):
    attributes: NotRequired[MalloryAIOpinionAttributesTypedDict]
    confidence: NotRequired[str]
    created_at: NotRequired[str]
    description: NotRequired[str]
    published_at: NotRequired[str]
    reference_source_slug: NotRequired[str]
    reference_url: NotRequired[str]
    reference_uuid: NotRequired[str]
    source: NotRequired[str]
    updated_at: NotRequired[str]
    uuid: NotRequired[str]
    verdict: NotRequired[str]


class MalloryAIOpinion(BaseModel):
    attributes: Optional[MalloryAIOpinionAttributes] = None

    confidence: Optional[str] = None

    created_at: Optional[str] = None

    description: Optional[str] = None

    published_at: Optional[str] = None

    reference_source_slug: Optional[str] = None

    reference_url: Optional[str] = None

    reference_uuid: Optional[str] = None

    source: Optional[str] = None

    updated_at: Optional[str] = None

    uuid: Optional[str] = None

    verdict: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "attributes",
                "confidence",
                "created_at",
                "description",
                "published_at",
                "reference_source_slug",
                "reference_url",
                "reference_uuid",
                "source",
                "updated_at",
                "uuid",
                "verdict",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
