"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .memberlist_nodeinfo import MemberlistNodeInfo, MemberlistNodeInfoTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MemberlistTypedDict(TypedDict):
    encrypted: NotRequired[bool]
    encrypted_len: NotRequired[int]
    encryption_version: NotRequired[int]
    error_message: NotRequired[str]
    node: NotRequired[MemberlistNodeInfoTypedDict]


class Memberlist(BaseModel):
    encrypted: Optional[bool] = None

    encrypted_len: Optional[int] = None

    encryption_version: Optional[int] = None

    error_message: Optional[str] = None

    node: Optional[MemberlistNodeInfo] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "encrypted",
                "encrypted_len",
                "encryption_version",
                "error_message",
                "node",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
