"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MinecraftTypedDict(TypedDict):
    motd: NotRequired[str]
    players_max: NotRequired[int]
    players_online: NotRequired[int]
    protocol_version: NotRequired[str]
    server_version: NotRequired[str]


class Minecraft(BaseModel):
    motd: Optional[str] = None

    players_max: Optional[int] = None

    players_online: Optional[int] = None

    protocol_version: Optional[str] = None

    server_version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "motd",
                "players_max",
                "players_online",
                "protocol_version",
                "server_version",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
