"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MoneroP2PResponseHeaderTypedDict(TypedDict):
    command: NotRequired[int]
    expects_response: NotRequired[bool]
    flags: NotRequired[int]
    length: NotRequired[int]
    return_code: NotRequired[int]
    signature: NotRequired[int]
    version: NotRequired[int]


class MoneroP2PResponseHeader(BaseModel):
    command: Optional[int] = None

    expects_response: Optional[bool] = None

    flags: Optional[int] = None

    length: Optional[int] = None

    return_code: Optional[int] = None

    signature: Optional[int] = None

    version: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "command",
                "expects_response",
                "flags",
                "length",
                "return_code",
                "signature",
                "version",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
