"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MongodbBuildInfoBuildEnvironmentTypedDict(TypedDict):
    cc: NotRequired[str]
    cc_flags: NotRequired[str]
    cxx: NotRequired[str]
    cxx_flags: NotRequired[str]
    dist_arch: NotRequired[str]
    dist_mod: NotRequired[str]
    link_flags: NotRequired[str]
    target_arch: NotRequired[str]
    target_os: NotRequired[str]


class MongodbBuildInfoBuildEnvironment(BaseModel):
    cc: Optional[str] = None

    cc_flags: Optional[str] = None

    cxx: Optional[str] = None

    cxx_flags: Optional[str] = None

    dist_arch: Optional[str] = None

    dist_mod: Optional[str] = None

    link_flags: Optional[str] = None

    target_arch: Optional[str] = None

    target_os: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "cc",
                "cc_flags",
                "cxx",
                "cxx_flags",
                "dist_arch",
                "dist_mod",
                "link_flags",
                "target_arch",
                "target_os",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
