"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .mplsldp_header import MplsLdpHeader, MplsLdpHeaderTypedDict
from .mplsldp_notification import MplsLdpNotification, MplsLdpNotificationTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MplsLdpTypedDict(TypedDict):
    header: NotRequired[MplsLdpHeaderTypedDict]
    notification: NotRequired[MplsLdpNotificationTypedDict]


class MplsLdp(BaseModel):
    header: Optional[MplsLdpHeader] = None

    notification: Optional[MplsLdpNotification] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["header", "notification"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
