"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class NodeInfoV1TypedDict(TypedDict):
    confirmed_milestone_index: NotRequired[int]
    features: NotRequired[Nullable[List[str]]]
    is_healthy: NotRequired[bool]
    latest_milestone_index: NotRequired[int]
    name: NotRequired[str]
    network_id: NotRequired[str]
    version: NotRequired[str]


class NodeInfoV1(BaseModel):
    confirmed_milestone_index: Optional[int] = None

    features: OptionalNullable[List[str]] = UNSET

    is_healthy: Optional[bool] = None

    latest_milestone_index: Optional[int] = None

    name: Optional[str] = None

    network_id: Optional[str] = None

    version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "confirmed_milestone_index",
                "features",
                "is_healthy",
                "latest_milestone_index",
                "name",
                "network_id",
                "version",
            ]
        )
        nullable_fields = set(["features"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
