"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ollama_model import OllamaModel, OllamaModelTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OllamaTypedDict(TypedDict):
    models: NotRequired[Nullable[List[OllamaModelTypedDict]]]
    running_models: NotRequired[Nullable[List[OllamaModelTypedDict]]]
    version: NotRequired[str]


class Ollama(BaseModel):
    models: OptionalNullable[List[OllamaModel]] = UNSET

    running_models: OptionalNullable[List[OllamaModel]] = UNSET

    version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["models", "running_models", "version"])
        nullable_fields = set(["models", "running_models"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
