"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .opcua_localizedtext import OpcUaLocalizedText, OpcUaLocalizedTextTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OpcUaDescriptionTypedDict(TypedDict):
    application_name: NotRequired[OpcUaLocalizedTextTypedDict]
    application_type: NotRequired[int]
    application_uri: NotRequired[str]
    discovery_profile_uri: NotRequired[str]
    discovery_urls: NotRequired[Nullable[List[str]]]
    gateway_server_uri: NotRequired[str]
    product_uri: NotRequired[str]


class OpcUaDescription(BaseModel):
    application_name: Optional[OpcUaLocalizedText] = None

    application_type: Optional[int] = None

    application_uri: Optional[str] = None

    discovery_profile_uri: Optional[str] = None

    discovery_urls: OptionalNullable[List[str]] = UNSET

    gateway_server_uri: Optional[str] = None

    product_uri: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "application_name",
                "application_type",
                "application_uri",
                "discovery_profile_uri",
                "discovery_urls",
                "gateway_server_uri",
                "product_uri",
            ]
        )
        nullable_fields = set(["discovery_urls"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
