"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .openflow_helloelement import OpenflowHelloElement, OpenflowHelloElementTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OpenflowTypedDict(TypedDict):
    auxiliary_id: NotRequired[int]
    bare_hello: NotRequired[bool]
    capabilities: NotRequired[Nullable[List[str]]]
    datapath_id: NotRequired[int]
    datapath_mac: NotRequired[str]
    dp_desc: NotRequired[str]
    hello_elements: NotRequired[Nullable[List[OpenflowHelloElementTypedDict]]]
    hw_desc: NotRequired[str]
    mfr_desc: NotRequired[str]
    n_buffers: NotRequired[int]
    n_tables: NotRequired[int]
    peer_role: NotRequired[str]
    protocol_version: NotRequired[str]
    protocol_version_raw: NotRequired[str]
    serial_num: NotRequired[str]
    sw_desc: NotRequired[str]
    xid: NotRequired[int]


class Openflow(BaseModel):
    auxiliary_id: Optional[int] = None

    bare_hello: Optional[bool] = None

    capabilities: OptionalNullable[List[str]] = UNSET

    datapath_id: Optional[int] = None

    datapath_mac: Optional[str] = None

    dp_desc: Optional[str] = None

    hello_elements: OptionalNullable[List[OpenflowHelloElement]] = UNSET

    hw_desc: Optional[str] = None

    mfr_desc: Optional[str] = None

    n_buffers: Optional[int] = None

    n_tables: Optional[int] = None

    peer_role: Optional[str] = None

    protocol_version: Optional[str] = None

    protocol_version_raw: Optional[str] = None

    serial_num: Optional[str] = None

    sw_desc: Optional[str] = None

    xid: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "auxiliary_id",
                "bare_hello",
                "capabilities",
                "datapath_id",
                "datapath_mac",
                "dp_desc",
                "hello_elements",
                "hw_desc",
                "mfr_desc",
                "n_buffers",
                "n_tables",
                "peer_role",
                "protocol_version",
                "protocol_version_raw",
                "serial_num",
                "sw_desc",
                "xid",
            ]
        )
        nullable_fields = set(["capabilities", "hello_elements"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
