"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .membermodulerole import MemberModuleRole, MemberModuleRoleTypedDict
from censys_platform.types import BaseModel, Nullable, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OrganizationMemberTypedDict(TypedDict):
    email: str
    r"""The email of the user."""
    first_name: str
    r"""The first name of the user."""
    last_name: str
    r"""The last name of the user."""
    roles: Nullable[List[str]]
    r"""The Platform-wide roles the user has in the organization."""
    uid: str
    r"""The ID of a Censys user."""
    created_at: NotRequired[datetime]
    r"""The date and time the user was created."""
    first_login_time: NotRequired[datetime]
    r"""The date and time the user first logged in."""
    latest_login_time: NotRequired[datetime]
    r"""The date and time the user last logged in."""
    module_roles: NotRequired[List[MemberModuleRoleTypedDict]]
    r"""The module roles this user holds. Empty when the user holds no module roles; absent when module roles could not be retrieved. A role in a module also grants access to the modules included with it; see included_with on the organization's modules."""


class OrganizationMember(BaseModel):
    email: str
    r"""The email of the user."""

    first_name: str
    r"""The first name of the user."""

    last_name: str
    r"""The last name of the user."""

    roles: Nullable[List[str]]
    r"""The Platform-wide roles the user has in the organization."""

    uid: str
    r"""The ID of a Censys user."""

    created_at: Optional[datetime] = None
    r"""The date and time the user was created."""

    first_login_time: Optional[datetime] = None
    r"""The date and time the user first logged in."""

    latest_login_time: Optional[datetime] = None
    r"""The date and time the user last logged in."""

    module_roles: Optional[List[MemberModuleRole]] = None
    r"""The module roles this user holds. Empty when the user holds no module roles; absent when module roles could not be retrieved. A role in a module also grants access to the modules included with it; see included_with on the organization's modules."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["created_at", "first_login_time", "latest_login_time", "module_roles"]
        )
        nullable_fields = set(["roles"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
