"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PgbouncerStartupCapabilitiesTypedDict(TypedDict):
    v2: NotRequired[bool]
    v3: NotRequired[bool]
    v4: NotRequired[bool]


class PgbouncerStartupCapabilities(BaseModel):
    v2: Optional[bool] = None

    v3: Optional[bool] = None

    v4: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["v2", "v3", "v4"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
