"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PortmapV3EntryTypedDict(TypedDict):
    description: NotRequired[str]
    network_id: NotRequired[str]
    owner: NotRequired[str]
    shorthand: NotRequired[str]
    universal_address: NotRequired[str]
    version: NotRequired[int]


class PortmapV3Entry(BaseModel):
    description: Optional[str] = None

    network_id: Optional[str] = None

    owner: Optional[str] = None

    shorthand: Optional[str] = None

    universal_address: Optional[str] = None

    version: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "network_id",
                "owner",
                "shorthand",
                "universal_address",
                "version",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
