"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PprofTypedDict(TypedDict):
    allocs: NotRequired[int]
    block: NotRequired[int]
    cmdline: NotRequired[str]
    goroutine: NotRequired[int]
    heap: NotRequired[int]
    mutex: NotRequired[int]
    profile: NotRequired[int]
    threadcreate: NotRequired[int]
    trace: NotRequired[int]


class Pprof(BaseModel):
    allocs: Optional[int] = None

    block: Optional[int] = None

    cmdline: Optional[str] = None

    goroutine: Optional[int] = None

    heap: Optional[int] = None

    mutex: Optional[int] = None

    profile: Optional[int] = None

    threadcreate: Optional[int] = None

    trace: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "allocs",
                "block",
                "cmdline",
                "goroutine",
                "heap",
                "mutex",
                "profile",
                "threadcreate",
                "trace",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
