"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .privacy_torinfo import PrivacyTorInfo, PrivacyTorInfoTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PrivacyTypedDict(TypedDict):
    anonymous: NotRequired[bool]
    r"""Whether the host uses any kind of privacy service."""
    proxy: NotRequired[bool]
    r"""Whether the host is an open web proxy."""
    relay: NotRequired[bool]
    r"""Whether the host is a location-preserving anonymous relay service, like iCloud Private Relay.."""
    service_provider: NotRequired[Nullable[List[str]]]
    r"""The name of the privacy service providers detected."""
    source: NotRequired[str]
    r"""The source of the data."""
    tor: NotRequired[bool]
    r"""Whether the host is a Tor exit node."""
    tor_info: NotRequired[PrivacyTorInfoTypedDict]
    vpn: NotRequired[bool]
    r"""Whether the host is a VPN service exit node IP address."""


class Privacy(BaseModel):
    anonymous: Optional[bool] = None
    r"""Whether the host uses any kind of privacy service."""

    proxy: Optional[bool] = None
    r"""Whether the host is an open web proxy."""

    relay: Optional[bool] = None
    r"""Whether the host is a location-preserving anonymous relay service, like iCloud Private Relay.."""

    service_provider: OptionalNullable[List[str]] = UNSET
    r"""The name of the privacy service providers detected."""

    source: Optional[str] = None
    r"""The source of the data."""

    tor: Optional[bool] = None
    r"""Whether the host is a Tor exit node."""

    tor_info: Optional[PrivacyTorInfo] = None

    vpn: Optional[bool] = None
    r"""Whether the host is a VPN service exit node IP address."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "anonymous",
                "proxy",
                "relay",
                "service_provider",
                "source",
                "tor",
                "tor_info",
                "vpn",
            ]
        )
        nullable_fields = set(["service_provider"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
