"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class PrivacyTorInfoRelayExitPolicySummaryTypedDict(TypedDict):
    accept: NotRequired[Nullable[List[str]]]
    r"""TCP ports or port ranges that the relay accepts for most IP addresses."""
    reject: NotRequired[Nullable[List[str]]]
    r"""TCP ports or port ranges that the relay rejects for most IP addresses."""


class PrivacyTorInfoRelayExitPolicySummary(BaseModel):
    accept: OptionalNullable[List[str]] = UNSET
    r"""TCP ports or port ranges that the relay accepts for most IP addresses."""

    reject: OptionalNullable[List[str]] = UNSET
    r"""TCP ports or port ranges that the relay rejects for most IP addresses."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["accept", "reject"])
        nullable_fields = set(["accept", "reject"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
