"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .privacy_torinfo_relay_exitpolicysummary import (
    PrivacyTorInfoRelayExitPolicySummary,
    PrivacyTorInfoRelayExitPolicySummaryTypedDict,
)
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PrivacyTorInfoRelayTypedDict(TypedDict):
    advertised_bandwidth: NotRequired[int]
    r"""Bandwidth in bytes per second that this relay is willing and capable to provide. The minimum of bandwidth_rate, bandwidth_burst, and observed_bandwidth."""
    alleged_family: NotRequired[Nullable[List[str]]]
    r"""Fingerprints of relays that are part of this relay's family but do not consider this relay to be part of their family."""
    bandwidth_burst: NotRequired[int]
    r"""Bandwidth in bytes per second that this relay is willing to sustain in very short intervals."""
    bandwidth_rate: NotRequired[int]
    r"""Average bandwidth in bytes per second that this relay is willing to sustain over long periods."""
    blocklist: NotRequired[Nullable[List[str]]]
    r"""Country codes where this bridge is not served because it is believed to be blocked."""
    bridge: NotRequired[bool]
    r"""Whether this entry represents a bridge rather than a relay."""
    bridgedb_distributor: NotRequired[str]
    r"""BridgeDB distributor that this bridge is currently assigned to."""
    consensus_weight: NotRequired[int]
    r"""Weight assigned to this relay by the directory authorities that clients use in their path selection algorithm."""
    consensus_weight_fraction: NotRequired[float]
    r"""Fraction of this relay's consensus weight compared to the sum of all consensus weights in the network. A rough approximation of the probability of this relay to be selected by clients."""
    contact: NotRequired[str]
    r"""Contact address of the relay operator."""
    dir_address: NotRequired[str]
    r"""IPv4 address and TCP port where the relay accepts directory connections."""
    effective_family: NotRequired[Nullable[List[str]]]
    r"""Fingerprints of relays in an effective, mutual family relationship with this relay. Always contains the relay's own fingerprint."""
    exit_addresses: NotRequired[Nullable[List[str]]]
    r"""IPv4 addresses that the relay used to exit to the Internet in the past 24 hours."""
    exit_policy: NotRequired[Nullable[List[str]]]
    r"""Array of exit-policy lines from the relay's router descriptor."""
    exit_policy_summary: NotRequired[PrivacyTorInfoRelayExitPolicySummaryTypedDict]
    exit_policy_v6_summary: NotRequired[PrivacyTorInfoRelayExitPolicySummaryTypedDict]
    exit_probability: NotRequired[float]
    r"""Probability of this relay to be selected for the exit position, calculated based on consensus weights, relay flags, and bandwidth weights."""
    fingerprint: NotRequired[str]
    r"""Relay fingerprint consisting of 40 upper-case hexadecimal characters."""
    flags: NotRequired[Nullable[List[str]]]
    r"""Relay flags assigned by the directory authorities."""
    guard_probability: NotRequired[float]
    r"""Probability of this relay to be selected for the guard position, calculated based on consensus weights, relay flags, and bandwidth weights."""
    hashed_fingerprint: NotRequired[str]
    r"""SHA-1 hash of the bridge fingerprint consisting of 40 upper-case hexadecimal characters."""
    indirect_family: NotRequired[Nullable[List[str]]]
    r"""Fingerprints of relays reachable by following effective, mutual family relationships starting at this relay, but not directly in a mutual family relationship."""
    measured: NotRequired[bool]
    r"""Whether the consensus weight of this relay is based on a threshold of 3 or more measurements by Tor bandwidth authorities."""
    middle_probability: NotRequired[float]
    r"""Probability of this relay to be selected for the middle position, calculated based on consensus weights, relay flags, and bandwidth weights."""
    nickname: NotRequired[str]
    r"""Relay nickname consisting of 1-19 alphanumerical characters."""
    observed_bandwidth: NotRequired[int]
    r"""Bandwidth estimate in bytes per second of the capacity this relay can handle. The lesser of the maximum sustained output and input over any ten second period in the past day."""
    or_addresses: NotRequired[Nullable[List[str]]]
    r"""IPv4 or IPv6 addresses and TCP ports where the relay accepts onion-routing connections. The first address is the primary onion-routing address."""
    overload_general_timestamp: NotRequired[int]
    r"""Timestamp indicating when the relay reached an overloaded state (e.g., OOM invocation, ntor onionskins dropped, or TCP port exhaustion)."""
    platform: NotRequired[str]
    r"""Platform string containing operating system and Tor version details."""
    recommended_version: NotRequired[bool]
    r"""Whether the Tor software version of this relay is recommended by the directory authorities."""
    transports: NotRequired[Nullable[List[str]]]
    r"""Pluggable transport names supported by this bridge."""
    unreachable_or_addresses: NotRequired[Nullable[List[str]]]
    r"""IPv4 or IPv6 addresses and TCP ports where the relay claims to accept onion-routing connections but that the directory authorities failed to confirm as reachable."""
    version: NotRequired[str]
    r"""Tor software version without leading 'Tor' as reported by the directory authorities."""
    version_status: NotRequired[str]
    r"""Status of the Tor software version: recommended, experimental, obsolete, new in series, or unrecommended."""


class PrivacyTorInfoRelay(BaseModel):
    advertised_bandwidth: Optional[int] = None
    r"""Bandwidth in bytes per second that this relay is willing and capable to provide. The minimum of bandwidth_rate, bandwidth_burst, and observed_bandwidth."""

    alleged_family: OptionalNullable[List[str]] = UNSET
    r"""Fingerprints of relays that are part of this relay's family but do not consider this relay to be part of their family."""

    bandwidth_burst: Optional[int] = None
    r"""Bandwidth in bytes per second that this relay is willing to sustain in very short intervals."""

    bandwidth_rate: Optional[int] = None
    r"""Average bandwidth in bytes per second that this relay is willing to sustain over long periods."""

    blocklist: OptionalNullable[List[str]] = UNSET
    r"""Country codes where this bridge is not served because it is believed to be blocked."""

    bridge: Optional[bool] = None
    r"""Whether this entry represents a bridge rather than a relay."""

    bridgedb_distributor: Optional[str] = None
    r"""BridgeDB distributor that this bridge is currently assigned to."""

    consensus_weight: Optional[int] = None
    r"""Weight assigned to this relay by the directory authorities that clients use in their path selection algorithm."""

    consensus_weight_fraction: Optional[float] = None
    r"""Fraction of this relay's consensus weight compared to the sum of all consensus weights in the network. A rough approximation of the probability of this relay to be selected by clients."""

    contact: Optional[str] = None
    r"""Contact address of the relay operator."""

    dir_address: Optional[str] = None
    r"""IPv4 address and TCP port where the relay accepts directory connections."""

    effective_family: OptionalNullable[List[str]] = UNSET
    r"""Fingerprints of relays in an effective, mutual family relationship with this relay. Always contains the relay's own fingerprint."""

    exit_addresses: OptionalNullable[List[str]] = UNSET
    r"""IPv4 addresses that the relay used to exit to the Internet in the past 24 hours."""

    exit_policy: OptionalNullable[List[str]] = UNSET
    r"""Array of exit-policy lines from the relay's router descriptor."""

    exit_policy_summary: Optional[PrivacyTorInfoRelayExitPolicySummary] = None

    exit_policy_v6_summary: Optional[PrivacyTorInfoRelayExitPolicySummary] = None

    exit_probability: Optional[float] = None
    r"""Probability of this relay to be selected for the exit position, calculated based on consensus weights, relay flags, and bandwidth weights."""

    fingerprint: Optional[str] = None
    r"""Relay fingerprint consisting of 40 upper-case hexadecimal characters."""

    flags: OptionalNullable[List[str]] = UNSET
    r"""Relay flags assigned by the directory authorities."""

    guard_probability: Optional[float] = None
    r"""Probability of this relay to be selected for the guard position, calculated based on consensus weights, relay flags, and bandwidth weights."""

    hashed_fingerprint: Optional[str] = None
    r"""SHA-1 hash of the bridge fingerprint consisting of 40 upper-case hexadecimal characters."""

    indirect_family: OptionalNullable[List[str]] = UNSET
    r"""Fingerprints of relays reachable by following effective, mutual family relationships starting at this relay, but not directly in a mutual family relationship."""

    measured: Optional[bool] = None
    r"""Whether the consensus weight of this relay is based on a threshold of 3 or more measurements by Tor bandwidth authorities."""

    middle_probability: Optional[float] = None
    r"""Probability of this relay to be selected for the middle position, calculated based on consensus weights, relay flags, and bandwidth weights."""

    nickname: Optional[str] = None
    r"""Relay nickname consisting of 1-19 alphanumerical characters."""

    observed_bandwidth: Optional[int] = None
    r"""Bandwidth estimate in bytes per second of the capacity this relay can handle. The lesser of the maximum sustained output and input over any ten second period in the past day."""

    or_addresses: OptionalNullable[List[str]] = UNSET
    r"""IPv4 or IPv6 addresses and TCP ports where the relay accepts onion-routing connections. The first address is the primary onion-routing address."""

    overload_general_timestamp: Optional[int] = None
    r"""Timestamp indicating when the relay reached an overloaded state (e.g., OOM invocation, ntor onionskins dropped, or TCP port exhaustion)."""

    platform: Optional[str] = None
    r"""Platform string containing operating system and Tor version details."""

    recommended_version: Optional[bool] = None
    r"""Whether the Tor software version of this relay is recommended by the directory authorities."""

    transports: OptionalNullable[List[str]] = UNSET
    r"""Pluggable transport names supported by this bridge."""

    unreachable_or_addresses: OptionalNullable[List[str]] = UNSET
    r"""IPv4 or IPv6 addresses and TCP ports where the relay claims to accept onion-routing connections but that the directory authorities failed to confirm as reachable."""

    version: Optional[str] = None
    r"""Tor software version without leading 'Tor' as reported by the directory authorities."""

    version_status: Optional[str] = None
    r"""Status of the Tor software version: recommended, experimental, obsolete, new in series, or unrecommended."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "advertised_bandwidth",
                "alleged_family",
                "bandwidth_burst",
                "bandwidth_rate",
                "blocklist",
                "bridge",
                "bridgedb_distributor",
                "consensus_weight",
                "consensus_weight_fraction",
                "contact",
                "dir_address",
                "effective_family",
                "exit_addresses",
                "exit_policy",
                "exit_policy_summary",
                "exit_policy_v6_summary",
                "exit_probability",
                "fingerprint",
                "flags",
                "guard_probability",
                "hashed_fingerprint",
                "indirect_family",
                "measured",
                "middle_probability",
                "nickname",
                "observed_bandwidth",
                "or_addresses",
                "overload_general_timestamp",
                "platform",
                "recommended_version",
                "transports",
                "unreachable_or_addresses",
                "version",
                "version_status",
            ]
        )
        nullable_fields = set(
            [
                "alleged_family",
                "blocklist",
                "effective_family",
                "exit_addresses",
                "exit_policy",
                "flags",
                "indirect_family",
                "or_addresses",
                "transports",
                "unreachable_or_addresses",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
