"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ProxmoxVeRealmTypedDict(TypedDict):
    comment: NotRequired[str]
    realm: NotRequired[str]
    tfa: NotRequired[str]
    type: NotRequired[str]


class ProxmoxVeRealm(BaseModel):
    comment: Optional[str] = None

    realm: Optional[str] = None

    tfa: Optional[str] = None

    type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["comment", "realm", "tfa", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
