"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class QcStatementsMonetaryValueTypedDict(TypedDict):
    amount: NotRequired[int]
    currency: NotRequired[str]
    currency_number: NotRequired[int]
    exponent: NotRequired[int]


class QcStatementsMonetaryValue(BaseModel):
    amount: Optional[int] = None

    currency: Optional[str] = None

    currency_number: Optional[int] = None

    exponent: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amount", "currency", "currency_number", "exponent"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
