"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class R1SoftBuagentTypedDict(TypedDict):
    cpu_hypervisor_signature: NotRequired[str]
    rsa_public_key_bits: NotRequired[int]
    rsa_public_key_sha256: NotRequired[str]


class R1SoftBuagent(BaseModel):
    cpu_hypervisor_signature: Optional[str] = None

    rsa_public_key_bits: Optional[int] = None

    rsa_public_key_sha256: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["cpu_hypervisor_signature", "rsa_public_key_bits", "rsa_public_key_sha256"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
