"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RdpProtocolFlagsTypedDict(TypedDict):
    dynvc_graphics_pipeline: NotRequired[bool]
    extended_client_data_supported: NotRequired[bool]
    neg_resp_reserved: NotRequired[bool]
    restricted_admin_mode: NotRequired[bool]
    restricted_auth_mode: NotRequired[bool]


class RdpProtocolFlags(BaseModel):
    dynvc_graphics_pipeline: Optional[bool] = None

    extended_client_data_supported: Optional[bool] = None

    neg_resp_reserved: Optional[bool] = None

    restricted_admin_mode: Optional[bool] = None

    restricted_auth_mode: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "dynvc_graphics_pipeline",
                "extended_client_data_supported",
                "neg_resp_reserved",
                "restricted_admin_mode",
                "restricted_auth_mode",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
