"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ReolinkBaichuanAlarmChannelTypedDict(TypedDict):
    ai_type: NotRequired[str]
    channel_id: NotRequired[int]
    recording: NotRequired[int]
    status: NotRequired[str]
    timestamp: NotRequired[int]


class ReolinkBaichuanAlarmChannel(BaseModel):
    ai_type: Optional[str] = None

    channel_id: Optional[int] = None

    recording: Optional[int] = None

    status: Optional[str] = None

    timestamp: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["ai_type", "channel_id", "recording", "status", "timestamp"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
