"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ReplayCapabilitiesTypedDict(TypedDict):
    reverse_playback: NotRequired[bool]
    rtp_rtsp_tcp: NotRequired[bool]
    session_timeout_range: NotRequired[str]


class ReplayCapabilities(BaseModel):
    reverse_playback: Optional[bool] = None

    rtp_rtsp_tcp: Optional[bool] = None

    session_timeout_range: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["reverse_playback", "rtp_rtsp_tcp", "session_timeout_range"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
