"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ReputationEvidenceFeatureTypedDict(TypedDict):
    category: NotRequired[str]
    contribution: NotRequired[float]
    id: NotRequired[str]
    name: NotRequired[str]
    value: NotRequired[str]


class ReputationEvidenceFeature(BaseModel):
    category: Optional[str] = None

    contribution: Optional[float] = None

    id: Optional[str] = None

    name: Optional[str] = None

    value: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["category", "contribution", "id", "name", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
