"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .reputation_evidence import ReputationEvidence, ReputationEvidenceTypedDict
from censys_platform import models, utils
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from enum import Enum
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ScoreLevel(str, Enum, metaclass=utils.OpenEnumMeta):
    UNKNOWN = ""
    BENIGN = "benign"
    LOW_RISK = "low_risk"
    MEDIUM_RISK = "medium_risk"
    HIGH_RISK = "high_risk"
    MALICIOUS = "malicious"


class ReputationTypedDict(TypedDict):
    evidence: NotRequired[Nullable[List[ReputationEvidenceTypedDict]]]
    model_version: NotRequired[str]
    score: NotRequired[float]
    score_level: NotRequired[ScoreLevel]


class Reputation(BaseModel):
    evidence: OptionalNullable[List[ReputationEvidence]] = UNSET

    model_version: Optional[str] = None

    score: Optional[float] = None

    score_level: Optional[ScoreLevel] = None

    @field_serializer("score_level")
    def serialize_score_level(self, value):
        if isinstance(value, str):
            try:
                return models.ScoreLevel(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["evidence", "model_version", "score", "score_level"])
        nullable_fields = set(["evidence"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
