"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rippleclioresults import RippleClioResults, RippleClioResultsTypedDict
from .rippledpublicresults import RippledPublicResults, RippledPublicResultsTypedDict
from .ripplepeerresults import RipplePeerResults, RipplePeerResultsTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RippleTypedDict(TypedDict):
    ripple_clio: NotRequired[RippleClioResultsTypedDict]
    rippled_peer: NotRequired[RipplePeerResultsTypedDict]
    rippled_public: NotRequired[RippledPublicResultsTypedDict]


class Ripple(BaseModel):
    ripple_clio: Optional[RippleClioResults] = None

    rippled_peer: Optional[RipplePeerResults] = None

    rippled_public: Optional[RippledPublicResults] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ripple_clio", "rippled_peer", "rippled_public"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
