"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .port import Port, PortTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RippledPublicResultsTypedDict(TypedDict):
    build_version: NotRequired[str]
    hostid: NotRequired[str]
    network_id: NotRequired[int]
    peers: NotRequired[int]
    ports: NotRequired[Nullable[List[PortTypedDict]]]
    pubkey_node: NotRequired[str]
    server_state: NotRequired[str]
    validation_quorum: NotRequired[int]


class RippledPublicResults(BaseModel):
    build_version: Optional[str] = None

    hostid: Optional[str] = None

    network_id: Optional[int] = None

    peers: Optional[int] = None

    ports: OptionalNullable[List[Port]] = UNSET

    pubkey_node: Optional[str] = None

    server_state: Optional[str] = None

    validation_quorum: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "build_version",
                "hostid",
                "network_id",
                "peers",
                "ports",
                "pubkey_node",
                "server_state",
                "validation_quorum",
            ]
        )
        nullable_fields = set(["ports"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
