"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RoutingTypedDict(TypedDict):
    asn: NotRequired[int]
    r"""The ASN (autonomous system number) of the host's autonomous system."""
    bgp_prefix: NotRequired[str]
    r"""The autonomous system's CIDR."""
    country_code: NotRequired[str]
    r"""The autonomous system's two-letter ISO 3166-1 alpha-2 country code (US, CN, GB, RU, ...)."""
    description: NotRequired[str]
    r"""Brief description of the autonomous system."""
    name: NotRequired[str]
    r"""The friendly name of the autonomous system."""
    organization: NotRequired[str]
    r"""The name of the organization managning the autonomous system."""


class Routing(BaseModel):
    asn: Optional[int] = None
    r"""The ASN (autonomous system number) of the host's autonomous system."""

    bgp_prefix: Optional[str] = None
    r"""The autonomous system's CIDR."""

    country_code: Optional[str] = None
    r"""The autonomous system's two-letter ISO 3166-1 alpha-2 country code (US, CN, GB, RU, ...)."""

    description: Optional[str] = None
    r"""Brief description of the autonomous system."""

    name: Optional[str] = None
    r"""The friendly name of the autonomous system."""

    organization: Optional[str] = None
    r"""The name of the organization managning the autonomous system."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["asn", "bgp_prefix", "country_code", "description", "name", "organization"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
