"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .saprouter_clientinfo import SapRouterClientInfo, SapRouterClientInfoTypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SapRouterRouterInfoTypedDict(TypedDict):
    connected_client_info: NotRequired[Nullable[List[SapRouterClientInfoTypedDict]]]
    num_clients: NotRequired[int]
    parent_pid: NotRequired[int]
    parent_port: NotRequired[int]
    pid: NotRequired[int]
    port: NotRequired[int]
    routtab_relative_directory: NotRequired[str]
    sap_router_absolute_directory: NotRequired[str]
    started_on: NotRequired[str]


class SapRouterRouterInfo(BaseModel):
    connected_client_info: OptionalNullable[List[SapRouterClientInfo]] = UNSET

    num_clients: Optional[int] = None

    parent_pid: Optional[int] = None

    parent_port: Optional[int] = None

    pid: Optional[int] = None

    port: Optional[int] = None

    routtab_relative_directory: Optional[str] = None

    sap_router_absolute_directory: Optional[str] = None

    started_on: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "connected_client_info",
                "num_clients",
                "parent_pid",
                "parent_port",
                "pid",
                "port",
                "routtab_relative_directory",
                "sap_router_absolute_directory",
                "started_on",
            ]
        )
        nullable_fields = set(["connected_client_info"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
