"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .saprouter_routerinfo import SapRouterRouterInfo, SapRouterRouterInfoTypedDict
from .saprouter_routerversioninfo import (
    SapRouterRouterVersionInfo,
    SapRouterRouterVersionInfoTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SapRouterTypedDict(TypedDict):
    router_info: NotRequired[SapRouterRouterInfoTypedDict]
    router_version_info: NotRequired[SapRouterRouterVersionInfoTypedDict]


class SapRouter(BaseModel):
    router_info: Optional[SapRouterRouterInfo] = None

    router_version_info: Optional[SapRouterRouterVersionInfo] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["router_info", "router_version_info"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
