"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ScreenshotTypedDict(TypedDict):
    extracted_text: NotRequired[str]
    handle: NotRequired[str]
    palsimhash: NotRequired[str]
    phash: NotRequired[str]


class Screenshot(BaseModel):
    extracted_text: Optional[str] = None

    handle: Optional[str] = None

    palsimhash: Optional[str] = None

    phash: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["extracted_text", "handle", "palsimhash", "phash"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
