"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class ServiceOnHostRangeTypedDict(TypedDict):
    end_time: datetime
    r"""When the service was last observed"""
    ip: str
    r"""IP address where the service was observed"""
    port: str
    r"""Port number where the service was observed"""
    protocol: str
    r"""Application protocol (e.g., HTTP, HTTPS)"""
    start_time: datetime
    r"""When the service was first observed"""
    transport_protocol: str
    r"""Transport protocol (e.g., TCP, UDP, QUIC)"""


class ServiceOnHostRange(BaseModel):
    end_time: datetime
    r"""When the service was last observed"""

    ip: str
    r"""IP address where the service was observed"""

    port: str
    r"""Port number where the service was observed"""

    protocol: str
    r"""Application protocol (e.g., HTTP, HTTPS)"""

    start_time: datetime
    r"""When the service was first observed"""

    transport_protocol: str
    r"""Transport protocol (e.g., TCP, UDP, QUIC)"""
