"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .signedcertificatetimestamp_signature import (
    SignedCertificateTimestampSignature,
    SignedCertificateTimestampSignatureTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SignedCertificateTimestampTypedDict(TypedDict):
    log_id: NotRequired[str]
    signature: NotRequired[SignedCertificateTimestampSignatureTypedDict]
    timestamp: NotRequired[str]
    version: NotRequired[int]


class SignedCertificateTimestamp(BaseModel):
    log_id: Optional[str] = None

    signature: Optional[SignedCertificateTimestampSignature] = None

    timestamp: Optional[str] = None

    version: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["log_id", "signature", "timestamp", "version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
