"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SnmpInterfacesTypedDict(TypedDict):
    num_ifaces: NotRequired[int]
    r"""1.3.6.1.2.1.2.1 - Number of network interfaces"""


class SnmpInterfaces(BaseModel):
    num_ifaces: Optional[int] = None
    r"""1.3.6.1.2.1.2.1 - Number of network interfaces"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["num_ifaces"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
