"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SnmpEngineTypedDict(TypedDict):
    description: NotRequired[str]
    engine_boots: NotRequired[int]
    engine_time: NotRequired[int]
    format_: NotRequired[str]
    format_data: NotRequired[str]
    organization: NotRequired[str]
    pen: NotRequired[int]
    raw_id: NotRequired[str]
    rfc3411: NotRequired[bool]


class SnmpEngine(BaseModel):
    description: Optional[str] = None

    engine_boots: Optional[int] = None

    engine_time: Optional[int] = None

    format_: Annotated[Optional[str], pydantic.Field(alias="format")] = None

    format_data: Optional[str] = None

    organization: Optional[str] = None

    pen: Optional[int] = None

    raw_id: Optional[str] = None

    rfc3411: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "engine_boots",
                "engine_time",
                "format",
                "format_data",
                "organization",
                "pen",
                "raw_id",
                "rfc3411",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SnmpEngine.model_rebuild()
except NameError:
    pass
