"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SocksTypedDict(TypedDict):
    no_authentication_required: NotRequired[bool]
    preferred_authentication: NotRequired[str]
    preferred_authentication_value: NotRequired[int]
    socks_version: NotRequired[int]


class Socks(BaseModel):
    no_authentication_required: Optional[bool] = None

    preferred_authentication: Optional[str] = None

    preferred_authentication_value: Optional[int] = None

    socks_version: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "no_authentication_required",
                "preferred_authentication",
                "preferred_authentication_value",
                "socks_version",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
