"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SourceUsageBreakdownTypedDict(TypedDict):
    api: int
    r"""The amount of credits consumed through the Platform API."""
    ui: int
    r"""The amount of credits consumed through the Platform UI."""
    auto_replenishment: NotRequired[int]
    r"""The amount of credits consumed through auto-replenishment."""
    other: NotRequired[int]
    r"""The amount of credits consumed through other operations."""


class SourceUsageBreakdown(BaseModel):
    api: int
    r"""The amount of credits consumed through the Platform API."""

    ui: int
    r"""The amount of credits consumed through the Platform UI."""

    auto_replenishment: Optional[int] = None
    r"""The amount of credits consumed through auto-replenishment."""

    other: Optional[int] = None
    r"""The amount of credits consumed through other operations."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auto_replenishment", "other"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
