"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SpiceTypedDict(TypedDict):
    major_version: NotRequired[int]
    minor_version: NotRequired[int]
    tls_only: NotRequired[bool]
    x509_public_key: NotRequired[str]


class Spice(BaseModel):
    major_version: Optional[int] = None

    minor_version: Optional[int] = None

    tls_only: Optional[bool] = None

    x509_public_key: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["major_version", "minor_version", "tls_only", "x509_public_key"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
