"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SpotifyConnectTypedDict(TypedDict):
    account_req: NotRequired[str]
    availability: NotRequired[str]
    device_id: NotRequired[str]
    group_status: NotRequired[str]
    model_display_name: NotRequired[str]
    public_key: NotRequired[str]
    remote_name: NotRequired[str]
    resolver_version: NotRequired[str]
    scope: NotRequired[str]
    status: NotRequired[str]
    token_type: NotRequired[str]
    version: NotRequired[str]
    voice_support: NotRequired[bool]


class SpotifyConnect(BaseModel):
    account_req: Optional[str] = None

    availability: Optional[str] = None

    device_id: Optional[str] = None

    group_status: Optional[str] = None

    model_display_name: Optional[str] = None

    public_key: Optional[str] = None

    remote_name: Optional[str] = None

    resolver_version: Optional[str] = None

    scope: Optional[str] = None

    status: Optional[str] = None

    token_type: Optional[str] = None

    version: Optional[str] = None

    voice_support: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "account_req",
                "availability",
                "device_id",
                "group_status",
                "model_display_name",
                "public_key",
                "remote_name",
                "resolver_version",
                "scope",
                "status",
                "token_type",
                "version",
                "voice_support",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
