"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .stun_bindingerrorresponse import (
    StunBindingErrorResponse,
    StunBindingErrorResponseTypedDict,
)
from .stun_bindingsuccessresponse import (
    StunBindingSuccessResponse,
    StunBindingSuccessResponseTypedDict,
)
from .stun_turn import StunTurn, StunTurnTypedDict
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class StunTypedDict(TypedDict):
    binding_error_response: NotRequired[StunBindingErrorResponseTypedDict]
    binding_success_response: NotRequired[StunBindingSuccessResponseTypedDict]
    response_type: NotRequired[int]
    response_type_name: NotRequired[str]
    turn: NotRequired[StunTurnTypedDict]


class Stun(BaseModel):
    binding_error_response: Optional[StunBindingErrorResponse] = None

    binding_success_response: Optional[StunBindingSuccessResponse] = None

    response_type: Optional[int] = None

    response_type_name: Optional[str] = None

    turn: Optional[StunTurn] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "binding_error_response",
                "binding_success_response",
                "response_type",
                "response_type_name",
                "turn",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
