"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TacacsPlusTypedDict(TypedDict):
    data_length: NotRequired[int]
    flags: NotRequired[int]
    obfuscated: NotRequired[str]
    seq_num: NotRequired[int]
    session_id: NotRequired[int]
    type: NotRequired[int]
    version: NotRequired[int]


class TacacsPlus(BaseModel):
    data_length: Optional[int] = None

    flags: Optional[int] = None

    obfuscated: Optional[str] = None

    seq_num: Optional[int] = None

    session_id: Optional[int] = None

    type: Optional[int] = None

    version: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "data_length",
                "flags",
                "obfuscated",
                "seq_num",
                "session_id",
                "type",
                "version",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
