"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TarantoolTypedDict(TypedDict):
    auth_type: NotRequired[str]
    error_code: NotRequired[int]
    error_file: NotRequired[str]
    error_message: NotRequired[str]
    error_type: NotRequired[str]
    instance_uuid: NotRequired[str]
    mode: NotRequired[str]
    response_error: NotRequired[str]
    server_features: NotRequired[Nullable[List[str]]]
    server_iproto_version: NotRequired[int]
    version: NotRequired[str]


class Tarantool(BaseModel):
    auth_type: Optional[str] = None

    error_code: Optional[int] = None

    error_file: Optional[str] = None

    error_message: Optional[str] = None

    error_type: Optional[str] = None

    instance_uuid: Optional[str] = None

    mode: Optional[str] = None

    response_error: Optional[str] = None

    server_features: OptionalNullable[List[str]] = UNSET

    server_iproto_version: Optional[int] = None

    version: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "auth_type",
                "error_code",
                "error_file",
                "error_message",
                "error_type",
                "instance_uuid",
                "mode",
                "response_error",
                "server_features",
                "server_iproto_version",
                "version",
            ]
        )
        nullable_fields = set(["server_features"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
