"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TargetTypedDict(TypedDict):
    alias: NotRequired[str]
    auths: NotRequired[Nullable[List[str]]]
    dns_portals: NotRequired[Nullable[List[str]]]
    errors: NotRequired[Nullable[List[str]]]
    name: NotRequired[str]
    private_portals: NotRequired[Nullable[List[str]]]
    public_portals: NotRequired[Nullable[List[str]]]


class Target(BaseModel):
    alias: Optional[str] = None

    auths: OptionalNullable[List[str]] = UNSET

    dns_portals: OptionalNullable[List[str]] = UNSET

    errors: OptionalNullable[List[str]] = UNSET

    name: Optional[str] = None

    private_portals: OptionalNullable[List[str]] = UNSET

    public_portals: OptionalNullable[List[str]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "alias",
                "auths",
                "dns_portals",
                "errors",
                "name",
                "private_portals",
                "public_portals",
            ]
        )
        nullable_fields = set(
            ["auths", "dns_portals", "errors", "private_portals", "public_portals"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
