"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TelexperTlxpTypedDict(TypedDict):
    frame_type: NotRequired[str]
    image_height_px: NotRequired[int]
    image_width_px: NotRequired[int]


class TelexperTlxp(BaseModel):
    frame_type: Optional[str] = None

    image_height_px: Optional[int] = None

    image_width_px: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["frame_type", "image_height_px", "image_width_px"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
