"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .malloryai import MalloryAI, MalloryAITypedDict
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class ThirdPartyTypedDict(TypedDict):
    mallory: NotRequired[Nullable[List[MalloryAITypedDict]]]
    r"""Threat intelligence records from MalloryAI."""


class ThirdParty(BaseModel):
    mallory: OptionalNullable[List[MalloryAI]] = UNSET
    r"""Threat intelligence records from MalloryAI."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mallory"])
        nullable_fields = set(["mallory"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
