"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TLSChainTypedDict(TypedDict):
    fingerprint_sha256: NotRequired[str]
    r"""SHA 256 fingerprint of the certificate in the certificate chain."""
    issuer_dn: NotRequired[str]
    r"""Distinguished name of the entity that has signed and issued the certificate."""
    subject_dn: NotRequired[str]
    r"""Distinguished name of the entity that the certificate belongs to."""


class TLSChain(BaseModel):
    fingerprint_sha256: Optional[str] = None
    r"""SHA 256 fingerprint of the certificate in the certificate chain."""

    issuer_dn: Optional[str] = None
    r"""Distinguished name of the entity that has signed and issued the certificate."""

    subject_dn: Optional[str] = None
    r"""Distinguished name of the entity that the certificate belongs to."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fingerprint_sha256", "issuer_dn", "subject_dn"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
