"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, Nullable, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class Roles(str, Enum):
    ADMIN = "admin"
    API_ACCESS = "api_access"


class UpdateMemberRoleInputBodyTypedDict(TypedDict):
    roles: Nullable[List[Roles]]
    r"""Array of role identifiers to assign to the user"""


class UpdateMemberRoleInputBody(BaseModel):
    roles: Nullable[List[Roles]]
    r"""Array of role identifiers to assign to the user"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
