"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .setmembermoduleroleinputbody import (
    SetMemberModuleRoleInputBody,
    SetMemberModuleRoleInputBodyTypedDict,
)
from censys_platform.types import BaseModel
from censys_platform.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class V3AccountmanagementSetMemberModuleRoleRequestTypedDict(TypedDict):
    organization_id: str
    r"""The ID of a Censys organization. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""
    user_id: str
    r"""The ID of a Censys user. You can obtain a user's ID by listing users in an organization."""
    module: str
    r"""The module identifier, for example platform-search."""
    set_member_module_role_input_body: SetMemberModuleRoleInputBodyTypedDict


class V3AccountmanagementSetMemberModuleRoleRequest(BaseModel):
    organization_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of a Censys organization. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""

    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of a Censys user. You can obtain a user's ID by listing users in an organization."""

    module: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The module identifier, for example platform-search."""

    set_member_module_role_input_body: Annotated[
        SetMemberModuleRoleInputBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class V3AccountmanagementSetMemberModuleRoleResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class V3AccountmanagementSetMemberModuleRoleResponse(BaseModel):
    headers: Dict[str, List[str]]
