"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responseenvelopecommentslist import (
    ResponseEnvelopeCommentsList,
    ResponseEnvelopeCommentsListTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from censys_platform.utils import FieldMetadata, QueryParamMetadata
from datetime import datetime
from enum import Enum
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3CommentsListCommentsGlobalsTypedDict(TypedDict):
    organization_id: NotRequired[str]


class V3CommentsListCommentsGlobals(BaseModel):
    organization_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["organization_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class OrderBy(str, Enum):
    r"""Sort order. Supported values: create_time_asc, create_time_desc."""

    CREATE_TIME_ASC = "create_time_asc"
    CREATE_TIME_DESC = "create_time_desc"


class V3CommentsListCommentsRequestTypedDict(TypedDict):
    organization_id: NotRequired[str]
    r"""The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""
    page_size: NotRequired[int]
    r"""Number of comments to return per page."""
    page_token: NotRequired[str]
    r"""Pagination token from a previous response to retrieve the next page of results."""
    order_by: NotRequired[OrderBy]
    r"""Sort order. Supported values: create_time_asc, create_time_desc."""
    asset_id: NotRequired[str]
    r"""Filter comments by asset identifier (host IP, certificate fingerprint, or web property hostname:port)."""
    created_by: NotRequired[str]
    r"""Filter comments by the user ID of the user who created the comment."""
    created_before: NotRequired[datetime]
    r"""Filter comments created before this RFC3339 timestamp."""
    created_after: NotRequired[datetime]
    r"""Filter comments created after this RFC3339 timestamp."""


class V3CommentsListCommentsRequest(BaseModel):
    organization_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = 100
    r"""Number of comments to return per page."""

    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Pagination token from a previous response to retrieve the next page of results."""

    order_by: Annotated[
        Optional[OrderBy],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = OrderBy.CREATE_TIME_DESC
    r"""Sort order. Supported values: create_time_asc, create_time_desc."""

    asset_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter comments by asset identifier (host IP, certificate fingerprint, or web property hostname:port)."""

    created_by: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter comments by the user ID of the user who created the comment."""

    created_before: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter comments created before this RFC3339 timestamp."""

    created_after: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter comments created after this RFC3339 timestamp."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "organization_id",
                "page_size",
                "page_token",
                "order_by",
                "asset_id",
                "created_by",
                "created_before",
                "created_after",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3CommentsListCommentsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ResponseEnvelopeCommentsListTypedDict


class V3CommentsListCommentsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ResponseEnvelopeCommentsList
