"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responseenvelopetagoperationslist import (
    ResponseEnvelopeTagOperationsList,
    ResponseEnvelopeTagOperationsListTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from censys_platform.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from enum import Enum
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3TagsListOperationsGlobalsTypedDict(TypedDict):
    organization_id: NotRequired[str]


class V3TagsListOperationsGlobals(BaseModel):
    organization_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["organization_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3TagsListOperationsQueryParamOrderBy(str, Enum):
    r"""Sort order. Supported values: create_time_asc, create_time_desc."""

    CREATE_TIME_ASC = "create_time_asc"
    CREATE_TIME_DESC = "create_time_desc"


class QueryParamType(str, Enum):
    r"""Filter by operation type."""

    BULK_CREATE = "bulk_create"
    BULK_DELETE = "bulk_delete"


class QueryParamStatus(str, Enum):
    r"""Filter by operation status."""

    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    LIMIT_REACHED = "limit_reached"
    FAILED = "failed"
    CANCELLED = "cancelled"


class V3TagsListOperationsRequestTypedDict(TypedDict):
    tag_id: str
    r"""The ID of the tag whose operations to list, or `-` to list operations across all tags in your organization."""
    organization_id: NotRequired[str]
    r"""The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""
    page_size: NotRequired[int]
    r"""Number of operations to return per page."""
    page_token: NotRequired[str]
    r"""Pagination token from a previous response to retrieve the next page of results."""
    order_by: NotRequired[V3TagsListOperationsQueryParamOrderBy]
    r"""Sort order. Supported values: create_time_asc, create_time_desc."""
    type: NotRequired[QueryParamType]
    r"""Filter by operation type."""
    status: NotRequired[QueryParamStatus]
    r"""Filter by operation status."""


class V3TagsListOperationsRequest(BaseModel):
    tag_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the tag whose operations to list, or `-` to list operations across all tags in your organization."""

    organization_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = 100
    r"""Number of operations to return per page."""

    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Pagination token from a previous response to retrieve the next page of results."""

    order_by: Annotated[
        Optional[V3TagsListOperationsQueryParamOrderBy],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = V3TagsListOperationsQueryParamOrderBy.CREATE_TIME_DESC
    r"""Sort order. Supported values: create_time_asc, create_time_desc."""

    type: Annotated[
        Optional[QueryParamType],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter by operation type."""

    status: Annotated[
        Optional[QueryParamStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter by operation status."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["organization_id", "page_size", "page_token", "order_by", "type", "status"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3TagsListOperationsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ResponseEnvelopeTagOperationsListTypedDict


class V3TagsListOperationsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ResponseEnvelopeTagOperationsList
