"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responseenvelopetagassignmentslist import (
    ResponseEnvelopeTagAssignmentsList,
    ResponseEnvelopeTagAssignmentsListTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from censys_platform.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from datetime import datetime
from enum import Enum
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3TagsListAssignmentsGlobalsTypedDict(TypedDict):
    organization_id: NotRequired[str]


class V3TagsListAssignmentsGlobals(BaseModel):
    organization_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["organization_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3TagsListAssignmentsQueryParamOrderBy(str, Enum):
    r"""Sort order. Supported values: create_time_asc, create_time_desc."""

    CREATE_TIME_ASC = "create_time_asc"
    CREATE_TIME_DESC = "create_time_desc"


class V3TagsListAssignmentsRequestTypedDict(TypedDict):
    tag_id: str
    r"""The ID of the tag whose assignments to list."""
    organization_id: NotRequired[str]
    r"""The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""
    page_size: NotRequired[int]
    r"""Number of assignments to return per page."""
    page_token: NotRequired[str]
    r"""Pagination token from a previous response to retrieve the next page of results."""
    order_by: NotRequired[V3TagsListAssignmentsQueryParamOrderBy]
    r"""Sort order. Supported values: create_time_asc, create_time_desc."""
    asset_id: NotRequired[str]
    r"""The identifier of the asset to tag (host IP, certificate SHA-256 fingerprint, or web property hostname:port)."""
    created_before: NotRequired[datetime]
    r"""RFC3339 timestamp. Only return assignments created before this time."""
    created_after: NotRequired[datetime]
    r"""RFC3339 timestamp. Only return assignments created after this time."""
    created_by: NotRequired[str]
    r"""Filter by the user ID of the user who created the assignment."""


class V3TagsListAssignmentsRequest(BaseModel):
    tag_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the tag whose assignments to list."""

    organization_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""

    page_size: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = 100
    r"""Number of assignments to return per page."""

    page_token: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Pagination token from a previous response to retrieve the next page of results."""

    order_by: Annotated[
        Optional[V3TagsListAssignmentsQueryParamOrderBy],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = V3TagsListAssignmentsQueryParamOrderBy.CREATE_TIME_DESC
    r"""Sort order. Supported values: create_time_asc, create_time_desc."""

    asset_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""The identifier of the asset to tag (host IP, certificate SHA-256 fingerprint, or web property hostname:port)."""

    created_before: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""RFC3339 timestamp. Only return assignments created before this time."""

    created_after: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""RFC3339 timestamp. Only return assignments created after this time."""

    created_by: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Filter by the user ID of the user who created the assignment."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "organization_id",
                "page_size",
                "page_token",
                "order_by",
                "asset_id",
                "created_before",
                "created_after",
                "created_by",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3TagsListAssignmentsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ResponseEnvelopeTagAssignmentsListTypedDict


class V3TagsListAssignmentsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ResponseEnvelopeTagAssignmentsList
