"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createinvestigationfileinputbody import (
    CreateInvestigationFileInputBody,
    CreateInvestigationFileInputBodyTypedDict,
)
from .responseenvelopeinvestigationfileupload import (
    ResponseEnvelopeInvestigationFileUpload,
    ResponseEnvelopeInvestigationFileUploadTypedDict,
)
from censys_platform.types import BaseModel, UNSET_SENTINEL
from censys_platform.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3ThreathuntingInvestigationsFilesCreateGlobalsTypedDict(TypedDict):
    organization_id: NotRequired[str]


class V3ThreathuntingInvestigationsFilesCreateGlobals(BaseModel):
    organization_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["organization_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3ThreathuntingInvestigationsFilesCreateRequestTypedDict(TypedDict):
    create_investigation_file_input_body: CreateInvestigationFileInputBodyTypedDict
    organization_id: NotRequired[str]
    r"""The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""


class V3ThreathuntingInvestigationsFilesCreateRequest(BaseModel):
    create_investigation_file_input_body: Annotated[
        CreateInvestigationFileInputBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    organization_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""The ID of a Censys organization to associate the request with. See the [Getting Started docs](https://docs.censys.com/reference/get-started#step-3-find-and-use-your-organization-id-optional) for more information."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["organization_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3ThreathuntingInvestigationsFilesCreateResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ResponseEnvelopeInvestigationFileUploadTypedDict


class V3ThreathuntingInvestigationsFilesCreateResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ResponseEnvelopeInvestigationFileUpload
