"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ValidityPeriodTypedDict(TypedDict):
    length_seconds: NotRequired[int]
    r"""The duration of the certificate's validity period, in seconds."""
    not_after: NotRequired[str]
    r"""An RFC-3339-formatted timestamp after which the certificate is no longer valid."""
    not_before: NotRequired[str]
    r"""An RFC-3339-formatted timestamp before which the certificate is not valid."""


class ValidityPeriod(BaseModel):
    length_seconds: Optional[int] = None
    r"""The duration of the certificate's validity period, in seconds."""

    not_after: Optional[str] = None
    r"""An RFC-3339-formatted timestamp after which the certificate is no longer valid."""

    not_before: Optional[str] = None
    r"""An RFC-3339-formatted timestamp before which the certificate is not valid."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["length_seconds", "not_after", "not_before"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
