"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cwe import Cwe, CweTypedDict
from .evidence import Evidence, EvidenceTypedDict
from .kev import Kev, KevTypedDict
from .metrics import Metrics, MetricsTypedDict
from censys_platform import models, utils
from censys_platform.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from enum import Enum
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class VulnRiskSource(str, Enum, metaclass=utils.OpenEnumMeta):
    UNKNOWN = ""
    CENSYS = "censys"
    CVE = "cve"


class VulnSeverity(str, Enum, metaclass=utils.OpenEnumMeta):
    UNKNOWN = ""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class VulnSource(str, Enum, metaclass=utils.OpenEnumMeta):
    UNKNOWN = ""
    CENSYS = "censys"
    RECOG = "recog"
    WAPPALYZER = "wappalyzer"
    THIRD_PARTY = "third_party"
    HTML_META_EXTRACTOR = "html_meta_extractor"


class VulnTypedDict(TypedDict):
    confidence: NotRequired[float]
    cwes: NotRequired[Nullable[List[CweTypedDict]]]
    evidence: NotRequired[Nullable[List[EvidenceTypedDict]]]
    id: NotRequired[str]
    kev: NotRequired[Nullable[List[KevTypedDict]]]
    metrics: NotRequired[MetricsTypedDict]
    name: NotRequired[str]
    risk_source: NotRequired[VulnRiskSource]
    severity: NotRequired[VulnSeverity]
    source: NotRequired[VulnSource]
    year: NotRequired[int]


class Vuln(BaseModel):
    confidence: Optional[float] = None

    cwes: OptionalNullable[List[Cwe]] = UNSET

    evidence: OptionalNullable[List[Evidence]] = UNSET

    id: Optional[str] = None

    kev: OptionalNullable[List[Kev]] = UNSET

    metrics: Optional[Metrics] = None

    name: Optional[str] = None

    risk_source: Optional[VulnRiskSource] = None

    severity: Optional[VulnSeverity] = None

    source: Optional[VulnSource] = None

    year: Optional[int] = None

    @field_serializer("risk_source")
    def serialize_risk_source(self, value):
        if isinstance(value, str):
            try:
                return models.VulnRiskSource(value)
            except ValueError:
                return value
        return value

    @field_serializer("severity")
    def serialize_severity(self, value):
        if isinstance(value, str):
            try:
                return models.VulnSeverity(value)
            except ValueError:
                return value
        return value

    @field_serializer("source")
    def serialize_source(self, value):
        if isinstance(value, str):
            try:
                return models.VulnSource(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "confidence",
                "cwes",
                "evidence",
                "id",
                "kev",
                "metrics",
                "name",
                "risk_source",
                "severity",
                "source",
                "year",
            ]
        )
        nullable_fields = set(["cwes", "evidence", "kev"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
