"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .webtimelineeventasset import WebTimelineEventAsset, WebTimelineEventAssetTypedDict
from censys_platform.types import BaseModel, Nullable, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class WebpropertyTimelineTypedDict(TypedDict):
    events: Nullable[List[WebTimelineEventAssetTypedDict]]
    scanned_to: datetime


class WebpropertyTimeline(BaseModel):
    events: Nullable[List[WebTimelineEventAsset]]

    scanned_to: datetime

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
