"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_sdk_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RSACryptographicKeyTypedDict(TypedDict):
    exponent: NotRequired[str]
    length: NotRequired[int]
    modulus: NotRequired[str]


class RSACryptographicKey(BaseModel):
    exponent: Optional[str] = None

    length: Optional[int] = None

    modulus: Optional[str] = None
