"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_sdk_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TeamViewerTypedDict(TypedDict):
    response: NotRequired[str]


class TeamViewer(BaseModel):
    response: Optional[str] = None
